import { useEffect, useState, type CSSProperties } from 'react';
import type { BroadcastState, Champion, Player, Scene, Side, Team } from '../../shared/types';
import { currentGameResult, frozenGameState, gameResultAwaitingTerminalSample, reportGameResult } from '../../shared/game-results';
import { championFor, getTeam, gold, playerCs, playerKda, time } from '../lib';
import { PlayerBuild } from './PlayerBuild';
import { dataDragonItemImage, useItemCatalog, type ItemAssets } from './useItemCatalog';
import { IncomeOverlay, NativeHudLayer, PlayerVitals } from './ObserverGraphics';
import { LiveBottom } from './LiveBottom';
import { LiveTop } from './LiveTop';
import { GameTime } from './GameTime';
import './broadcast-skins.css';
import './observer-graphics.css';

export function ChampionImage({champions,id,kind='icon',className=''}:{champions:Champion[];id:string;kind?:'icon'|'splash';className?:string}) {
  const champion=championFor(champions,id);
  return <div className={`champion-image ${className}`}>{champion?<img loading="lazy" src={kind==='splash'?champion.splash:champion.image} alt={champion.name} onError={e=>{e.currentTarget.style.visibility='hidden';}}/>:<span>{id?.slice(0,2)||'—'}</span>}</div>;
}
export function economySource(state:BroadcastState) {
  if(state.mode==='demo')return '演示数据';
  return ({api:'客户端 API',ocr:'观战 HUD 读数',manual:'人工校准',none:'等待经济数据源'} as const)[state.economyFeed?.source||'none'];
}
export function EconomyChart({state,compact=false}:{state:BroadcastState;compact?:boolean}) {
  const points=state.economy;const max=Math.max(2000,...points.map(p=>Math.abs(p.blue-p.red)))*1.2;
  const end=Math.max(1,state.gameTime,points.at(-1)?.time??0);
  const coords=points.map(p=>`${40+p.time/end*710},${105-(p.blue-p.red)/max*80}`).join(' ');
  const last=points.at(-1);const delta=last?last.blue-last.red:0;
  return <div className={`economy-chart ${compact?'compact':''}`}><svg viewBox="0 0 800 240" role="img" aria-label="双方经济差曲线，正值代表蓝色方领先">{[25,65,105,145,185].map((y,i)=><g key={y}><line x1="40" x2="755" y1={y} y2={y} stroke="currentColor" strokeOpacity={i===2?'.3':'.12'} strokeDasharray={i===2?'0':'3 5'}/><text x="3" y={y+4} fill="currentColor" opacity=".6" fontSize="12">{i===2?'0':`${i<2?'+':'−'}${Math.round(max*(Math.abs(2-i)/2)/1000)}k`}</text></g>)}{points.length===1&&<circle cx={40+points[0].time/end*710} cy={105-(points[0].blue-points[0].red)/max*80} r="4" fill="var(--cast-blue, #36a9e7)"/>}{points.length>1&&<><polygon points={`40,105 ${coords} ${40+(last?.time??0)/end*710},105`} fill="currentColor" opacity=".09"/><polyline points={coords} fill="none" stroke={delta>=0?'var(--cast-blue, #36a9e7)':'var(--cast-red, #eb5264)'} strokeWidth="3" strokeLinejoin="round"/></>}{[0,.25,.5,.75,1].map(t=><text key={t} x={40+t*710} y="220" textAnchor="middle" fill="currentColor" opacity=".55" fontSize="12">{time(end*t)}</text>)}</svg>{!points.length&&<div className="chart-unavailable">经济曲线等待数据</div>}{points.length===1&&<div className="chart-one-point">已采集 1 个点，继续观战生成曲线</div>}</div>;
}
function TeamMark({team,className=''}:{team?:Team;className?:string}) {return <span className={`cast-team-mark ${className}`} title={team?.name}>{team?.logo?<img src={team.logo} alt={`${team.name} 队标`}/>:<b>{team?.tag?.slice(0,1)||'?'}</b>}</span>;}
function TournamentMark({state,small=false}:{state:BroadcastState;small?:boolean}) {return <div className={`cast-tournament ${small?'small':''}`} title={state.match.title}><svg className="cast-emblem" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 2 22 8v8l-10 6L2 16V8L12 2Z" stroke="currentColor" strokeWidth="1.6"/><path d="m7 8 5-3 5 3-5 3-5-3Zm0 4 5 3 5-3M12 11v8" stroke="currentColor" strokeWidth="1.6" strokeLinejoin="round"/></svg><div><b>RIFTCAST <span>/ ARENA</span></b><small>LEAGUE OF LEGENDS · MATCH BROADCAST</small></div></div>;}
const roleNames=['TOP','JUNGLE','MID','BOT','SUPPORT'];
function sidePlayers(state:BroadcastState,side:Side) {return state.players.filter(p=>p.team===side).slice(0,5);}
function teamKills(state:BroadcastState,side:Side) {const players=sidePlayers(state,side);return state.mode==='live'&&(!players.length||players.some(p=>p.statsAvailable===false))?'—':state.stats[side].kills;}
function portraitFor(state:BroadcastState,player:Player|undefined,side:Side,index:number) {return player?.portrait||getTeam(state,side)?.players.find(p=>p.name===player?.name)?.portrait||getTeam(state,side)?.players[index]?.portrait;}
function Equipment({player,items,version}:{player?:Player;items:ItemAssets;version:string}) {const slots=player?.itemSlots||player?.items||[];return <div className="cast-equipment">{Array.from({length:7},(_,i)=>{const id=slots[i]||0;const src=items[id]?.image||dataDragonItemImage(version,id);return <span key={i} className={i===6?'cast-trinket':''} title={id?(items[id]?.name||'装备图标加载中'):i===6?'空饰品栏':'空装备栏'}>{src?<img src={src} alt={items[id]?.name||(i===6?'饰品':'装备')} onError={e=>{e.currentTarget.style.visibility='hidden';}}/>:null}</span>;})}</div>;}
function ObserverRow({player,champions,side,items,version}:{player?:Player;champions:Champion[];side:Side;items:ItemAssets;version:string}) {
  return <div className={`cast-observer-row ${side}`}><Equipment player={player} items={items} version={version}/><span className="cast-observer-cs">{playerCs(player)}</span><ChampionImage champions={champions} id={player?.championId||''}/><span className="cast-observer-id"><strong>{player?.name||'等待选手'}</strong><small>LV {player?.level||'—'}</small><PlayerVitals player={player}/></span><b>{playerKda(player,true)}</b></div>;
}
function ObserverTable({state,champions,items,version}:{state:BroadcastState;champions:Champion[];items:ItemAssets;version:string}) {
  const blue=sidePlayers(state,'blue'),red=sidePlayers(state,'red');
  return <div className="cast-observer-table" aria-label="十名选手装备与数据"><header><span>{getTeam(state,'blue')?.tag} · ITEMS / CS / KDA</span><b>GAME {state.match.game}</b><span>KDA / CS / ITEMS · {getTeam(state,'red')?.tag}</span></header>{Array.from({length:5},(_,i)=><div className="cast-observer-pair" key={i}><ObserverRow player={blue[i]} champions={champions} side="blue" items={items} version={version}/><span className="cast-observer-role">{['T','J','M','B','S'][i]}</span><ObserverRow player={red[i]} champions={champions} side="red" items={items} version={version}/></div>)}</div>;
}
function CapturePreview({scene}:{scene:Scene}) {return <div className={`cast-capture-preview capture-${scene}`}><div className="cast-feed-symbol" aria-hidden="true"><span/><span/><span/><span/></div><span>{scene==='draft'?'选手 / 舞台画面':scene==='interview'?'赛后采访画面':scene==='teamfight'?'游戏原生团战视角':'游戏观战画面'}</span><small>{scene==='teamfight'?'切入团战后，在游戏观战窗口按 A 切换原生视角':'RIFTCAST ARENA / 在连接与输出查看合成画面'}</small></div>;}
function BanStrip({state,champions,side}:{state:BroadcastState;champions:Champion[];side:Side}) {const ids=state.draft[side==='blue'?'blueBans':'redBans'];const teamId=state.match[`${side}TeamId`];const history=(state.draftHistory||[]).filter(g=>g.seriesId===state.match.seriesId&&g.game<state.match.game&&(g.blueTeamId===teamId||g.redTeamId===teamId)).sort((a,b)=>a.game-b.game);return <div className={`cast-ban-history ${side}`} aria-label={`${side==='blue'?'蓝':'红'}方全局 BP 历史`}>{history.map(g=><div className="cast-history-game" key={g.game}><span>GAME {g.game} · 已选禁用</span><div>{(g.blueTeamId===teamId?g.bluePicks:g.redPicks).map((id,i)=><ChampionImage key={i} champions={champions} id={id}/>)}</div></div>)}<div className={`cast-bans ${side}`}><span>GAME {state.match.game} · BANS</span><div>{Array.from({length:5},(_,i)=><ChampionImage key={i} champions={champions} id={ids[i]||''}/>)}</div></div></div>;}
function DraftCards({state,champions,side}:{state:BroadcastState;champions:Champion[];side:Side}) {
 const team=getTeam(state,side),picks=state.draft[side==='blue'?'bluePicks':'redPicks'];
 return <div className={`cast-draft-team ${side}`}><BanStrip state={state} champions={champions} side={side}/><div className="cast-draft-cards">{Array.from({length:5},(_,i)=><div className={`cast-draft-card ${picks[i]?'locked':'waiting'}`} key={i}><ChampionImage champions={champions} id={picks[i]||''} kind="splash"/><small className="cast-pick-order">{side==='blue'?'B':'R'}{i+1}</small><span className="cast-draft-role">{roleNames[i]}</span><strong className="cast-draft-player">{team?.players[i]?.name||`PLAYER ${i+1}`}</strong><span className="cast-draft-champion">{championFor(champions,picks[i])?.name||'等待选择'}</span></div>)}</div></div>;
}
function DraftOverlay({state,champions}:{state:BroadcastState;champions:Champion[]}) {const blue=getTeam(state,'blue'),red=getTeam(state,'red');return <div className="cast-draft"><DraftCards state={state} champions={champions} side="blue"/><div className="cast-draft-center"><TournamentMark state={state} small/><div className="cast-draft-versus"><b>{blue?.tag}</b><span>{state.match.blueScore} : {state.match.redScore}</span><b>{red?.tag}</b></div><div className={`cast-draft-timer ${state.draft.activeTeam}`}><strong>{Math.ceil(state.draft.timer)}</strong><small>{state.draft.activeTeam==='blue'?blue?.tag:red?.tag} · {state.draft.action||'选人'}</small></div><small className="cast-draft-game">{state.match.format} / GAME {state.match.game}</small></div><DraftCards state={state} champions={champions} side="red"/></div>;}
function GraphicHeader({state,title,eyebrow}:{state:BroadcastState;title:string;eyebrow:string}) {return <header className="cast-graphic-header"><TournamentMark state={state}/><div><small>{eyebrow}</small><strong>{title}</strong></div><span>{state.match.format} · GAME {state.match.game}</span></header>;}
function Standby({state,now}:{state:BroadcastState;now:number}) {const blue=getTeam(state,'blue'),red=getTeam(state,'red');return <div className="cast-standby"><GraphicHeader state={state} title={state.match.title} eyebrow="MATCH DAY"/><div className="cast-opener-type" aria-hidden="true">GAME<br/>ON.</div><div className="cast-standby-match"><div className="blue"><TeamMark team={blue}/><strong>{blue?.tag}</strong><span>{blue?.name}</span></div><div className="cast-standby-versus"><small>{state.match.subtitle}</small><strong>VS</strong><span>{state.match.blueScore} — {state.match.redScore}</span></div><div className="red"><TeamMark team={red}/><strong>{red?.tag}</strong><span>{red?.name}</span></div></div><div className="cast-countdown"><span>比赛即将开始 / STARTING SOON</span><strong>{time(state.overlay.countdownEnd?Math.max(0,(state.overlay.countdownEnd-now)/1000):0)}</strong><small>{state.match.format} · GAME {state.match.game}</small></div><div className="cast-opener-bottom"><span>{state.match.title}</span><b>PRE MATCH</b><span>{state.mode==='demo'?'演示对局':'本地赛事转播'}</span></div></div>;}
function Lineup({state,champions}:{state:BroadcastState;champions:Champion[]}) {return <div className="cast-lineup"><GraphicHeader state={state} title="首发阵容与对位" eyebrow="STARTING LINEUP"/><div className="cast-lineup-sides">{(['blue','red'] as Side[]).map(side=>{const team=getTeam(state,side),players=sidePlayers(state,side),picks=state.draft[side==='blue'?'bluePicks':'redPicks'];return <section className={`cast-lineup-side ${side}`} key={side}><h2><TeamMark team={team}/><strong>{team?.tag}</strong><span>{team?.name}</span></h2><div className="cast-lineup-five">{Array.from({length:5},(_,i)=>{const p=players[i],photo=portraitFor(state,p,side,i),id=p?.championId||picks[i]||'';return <article key={i}><div className="cast-lineup-photo">{photo?<img src={photo} alt={`${p?.name||team?.players[i]?.name} 选手照片`}/>:<ChampionImage champions={champions} id={id} kind="splash"/>}<span>{roleNames[i]}</span></div><strong>{p?.name||team?.players[i]?.name||'待录入'}</strong><small>{championFor(champions,id)?.name||'英雄待定'}</small></article>;})}</div></section>;})}</div><footer className="cast-lineup-bottom"><b>{getTeam(state,'blue')?.tag}</b><span>{state.match.blueScore} — {state.match.redScore}<small>{state.match.format} · GAME {state.match.game}</small></span><b>{getTeam(state,'red')?.tag}</b></footer></div>;}
function EconomyOverlay({state}:{state:BroadcastState}) {const blue=getTeam(state,'blue'),red=getTeam(state,'red'),delta=state.stats.blue.gold!=null&&state.stats.red.gold!=null?state.stats.blue.gold-state.stats.red.gold:null;return <div className="cast-analysis cast-economy"><header><span>GOLD DIFFERENCE</span><strong>团队经济走势</strong><b><GameTime state={state}/></b></header><div className="cast-economy-values"><span className="blue">{blue?.tag} <b>{gold(state.stats.blue.gold)}</b></span><strong>{delta!=null?`${delta>=0?'+':''}${gold(delta)}`:'—'}</strong><span className="red"><b>{gold(state.stats.red.gold)}</b> {red?.tag}</span></div><EconomyChart state={state}/><footer><span>来源：{economySource(state)}</span><small>{state.economyFeed?.source==='ocr'?'按观战 HUD 显示精度采样':state.economyFeed?.source==='manual'?'按导播人工输入采样':'BLUE LEAD ↑ / RED LEAD ↓'}</small></footer></div>;}
function Performance({state,champions,items,version}:{state:BroadcastState;champions:Champion[];items:ItemAssets;version:string}) {const players=[...state.players].sort((a,b)=>a.statsAvailable===false?(b.statsAvailable===false?0:1):b.statsAvailable===false?-1:(b.kills+b.assists)/Math.max(1,b.deaths)-(a.kills+a.assists)/Math.max(1,a.deaths)).slice(0,10);return <div className="cast-analysis cast-performance"><header><span>PLAYER PERFORMANCE</span><strong>{currentGameResult(state)?`第 ${state.match.game} 局${gameResultAwaitingTerminalSample(currentGameResult(state))?'已保存':'最终'}选手数据`:'选手数据 / KDA 排序'}</strong><b><GameTime state={state}/></b></header><div className="cast-performance-head"><span>选手 / 英雄</span><span>K / D / A</span><span>CS</span><span>LV</span><span>个人经济</span><span>装备</span></div>{players.map((p,i)=><div className={`cast-performance-row ${p.team}`} key={p.id}><span><em>{p.statsAvailable===false?'—':String(i+1).padStart(2,'0')}</em><ChampionImage champions={champions} id={p.championId}/><strong>{p.name}</strong></span><b>{playerKda(p)}</b><span>{playerCs(p)}</span><span>{p.level}</span><span>{gold(p.gold)}</span><Equipment player={p} items={items} version={version}/></div>)}<footer>个人累计经济来自客户端累计字段或原生观战金币列 · 装备栏独立显示</footer></div>;}
function Schedule({state}:{state:BroadcastState}) {return <div className="cast-schedule"><GraphicHeader state={state} title="赛事赛程" eyebrow="MATCH SCHEDULE"/><div className="cast-schedule-heading"><strong>MATCH<br/>SCHEDULE</strong><span>{state.match.title}<small>所有时间为北京时间</small></span></div><div className="cast-schedule-list">{state.schedule.slice(0,4).map((m,i)=>{const blue=state.teams.find(t=>t.id===m.blueTeamId),red=state.teams.find(t=>t.id===m.redTeamId);return <div className={`cast-schedule-row ${m.status}`} key={m.id}><small>{String(i+1).padStart(2,'0')}</small><time>{new Date(m.scheduledAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}</time><span><TeamMark team={blue}/><b>{blue?.tag||'TBD'}</b></span><strong>{m.status==='scheduled'?'VS':`${m.blueScore} : ${m.redScore}`}</strong><span><b>{red?.tag||'TBD'}</b><TeamMark team={red}/></span><em>{m.status==='live'?'LIVE':m.status==='finished'?'FINAL':m.format}</em></div>;})}{!state.schedule.length&&<p className="cast-empty">在赛事管理中录入赛程</p>}</div></div>;}
function Postgame({state,champions,items,version}:{state:BroadcastState;champions:Champion[];items:ItemAssets;version:string}) {const blue=getTeam(state,'blue'),red=getTeam(state,'red');return <div className="cast-postgame"><GraphicHeader state={state} title={currentGameResult(state)?`第 ${state.match.game} 局赛后数据报告 · ${gameResultAwaitingTerminalSample(currentGameResult(state))?'等待终局样本':'已冻结'}`:'赛后数据报告'} eyebrow="POST GAME REPORT"/><div className="cast-result"><div className="blue"><TeamMark team={blue}/><strong>{blue?.tag}</strong></div><span><b>{state.match.blueScore} — {state.match.redScore}</b><small>系列赛比分 · {state.match.format} · GAME {state.match.game}</small><em>对局时长 <GameTime state={state}/></em></span><div className="red"><strong>{red?.tag}</strong><TeamMark team={red}/></div></div><div className="cast-team-comparison">{[['击杀',teamKills(state,'blue'),teamKills(state,'red')],['团队经济',gold(state.stats.blue.gold),gold(state.stats.red.gold)],['防御塔',state.stats.blue.towers,state.stats.red.towers],['小龙',state.stats.blue.dragons,state.stats.red.dragons],['大龙',state.stats.blue.barons,state.stats.red.barons]].map(([label,b,r])=><div key={label}><b className="blue">{b}</b><span>{label}</span><b className="red">{r}</b></div>)}</div><div className="cast-report-teams">{(['blue','red'] as Side[]).map(side=><section className={side} key={side}><header><span>PLAYER / CHAMPION</span><span>K / D / A</span><span>CS</span><span>GOLD</span></header>{sidePlayers(state,side).map(p=><div key={p.id}><span><ChampionImage champions={champions} id={p.championId}/><strong>{p.name}</strong><Equipment player={p} items={items} version={version}/></span><b>{playerKda(p)}</b><span>{playerCs(p)}</span><span>{gold(p.gold)}</span></div>)}</section>)}</div><footer><span>团队经济来源：{economySource(state)}</span><span>{state.match.title}</span><span>{state.mode==='demo'?'DEMO DATA':'LOCAL MATCH DATA'}</span></footer></div>;}
function Interview({state}:{state:BroadcastState}) {const player=state.players.find(p=>p.id===state.selectedPlayerId),team=player?getTeam(state,player.team):undefined;return <div className="cast-interview"><TournamentMark state={state} small/><span className="cast-interview-name"><small>POST MATCH INTERVIEW / 赛后采访</small><strong>{player?.name||'赛后采访'}</strong><span>{team?.tag||state.match.title}{team?' · '+team.name:''}</span></span><b>{state.match.format}<small>GAME {state.match.game}</small></b></div>;}
export function BroadcastCanvas({state:sourceState,champions,scene,output=false}:{state:BroadcastState;champions:Champion[];scene:Scene;output?:boolean}) {
 const frozenResult=['ranking','postgame'].includes(scene)?currentGameResult(sourceState)||reportGameResult(sourceState):undefined;
 const state=frozenResult?frozenGameState(sourceState,frozenResult):sourceState;
 const [now,setNow]=useState(Date.now());const {version,items}=useItemCatalog(scene==='teamfight'?[]:champions);
 useEffect(()=>{if(scene!=='standby'&&scene!=='live')return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[scene]);
 // The game's A view supplies the teamfight HUD. Keep the OBS layer fully transparent.
 if(scene==='teamfight')return <div className={`broadcast-container cast-container skin-arena ${output?'is-output':''}`}><div className="broadcast-canvas cast-canvas cast-scene-teamfight transparent cast-transparent" aria-label="游戏原生团战视角">{!output&&<CapturePreview scene={scene}/>}</div></div>;
 const liveScene=['live','income','economy','ranking'].includes(scene);
 const overlayScene=['draft','live','income','economy','ranking','interview'].includes(scene),selected=state.players.some(p=>p.id===state.selectedPlayerId);
 const feed=scene==='draft'||scene==='lineup'?state.connections.lcu:state.connections.live;
 const sourceIssue=!frozenResult&&state.mode==='live'&&['live','teamfight','income','draft','lineup','economy','ranking'].includes(scene)&&feed.status!=='connected';
 return <div className={`broadcast-container cast-container skin-arena ${output?'is-output':''}`} style={{'--broadcast-accent':state.overlay.accent} as CSSProperties}><div className={`broadcast-canvas cast-canvas cast-scene-${scene} ${state.overlay.ticker?'has-ticker':''} ${overlayScene&&output?'transparent cast-transparent':''}`} style={{'--hud-scale':state.overlay.scale} as CSSProperties}>
 {overlayScene&&!output&&<CapturePreview scene={scene}/>}
 {liveScene&&<NativeHudLayer state={state}/>}
 {scene==='live'&&<LiveBottom state={state} champions={champions} items={items} version={version}/>}
 {scene==='standby'&&<Standby state={state} now={now}/>}
 {scene==='draft'&&<DraftOverlay state={state} champions={champions}/>}
 {scene==='lineup'&&<Lineup state={state} champions={champions}/>}
 {liveScene&&state.overlay.scoreboard&&<LiveTop state={state}/>}
 {scene==='income'&&<IncomeOverlay state={state} champions={champions}/>}
 {scene==='economy'&&<EconomyOverlay state={state}/>}
 {scene==='ranking'&&(selected?<PlayerBuild state={state} champions={champions} output/>:<Performance state={state} champions={champions} items={items} version={version}/>)}
 {scene==='schedule'&&<Schedule state={state}/>}
 {scene==='postgame'&&<Postgame state={state} champions={champions} items={items} version={version}/>}
 {scene==='interview'&&<Interview state={state}/>}
 {scene!=='income'&&(state.overlay.sponsor||state.overlay.sponsorLogo)&&<div className="cast-sponsor">{state.overlay.sponsorLogo?<img src={state.overlay.sponsorLogo} alt={state.overlay.sponsor||'赞助商标志'}/>:<span>{state.overlay.sponsor}</span>}</div>}
 {state.overlay.ticker&&<div className="cast-ticker"><b>{state.match.title}</b><span>{state.overlay.tickerText}</span></div>}
 {state.mode==='demo'&&<span className="cast-demo">DEMO · 演示数据</span>}
 {sourceIssue&&<div className="cast-source-status">{feed.updatedAt?'客户端数据中断':'等待客户端数据'}{feed.updatedAt&&<span> · 截至 {new Date(feed.updatedAt).toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})}</span>}</div>}
 </div></div>;
}
