import {economySegments} from '../../shared/presentation';
import {schedulePage} from '../../shared/schedule-view';
import { championArtwork } from '../../shared/champion-art';
import { GoldRankingOverlay } from './GoldRanking';
import { useEffect, useState, type CSSProperties } from 'react';
import type { BroadcastState, Champion, Player, Scene, Side, Team } from '../../shared/types';
import { currentGameResult, frozenGameState, gameResultAwaitingTerminalSample, reportGameResult } from '../../shared/game-results';
import { championFor, getTeam, gold, playerCs, playerKda, time } from '../lib';
import { PlayerBuild } from './PlayerBuild';
import { dataDragonItemImage, useItemCatalog, type ItemAssets } from './useItemCatalog';
import { NativeHudLayer, PlayerVitals } from './ObserverGraphics';
import { LiveBottom } from './LiveBottom';
import { LiveTop } from './LiveTop';
import { GameTime } from './GameTime';
import './broadcast-skins.css';
import './observer-graphics.css';

export function ChampionImage({champions,id,kind='icon',art='draft',className=''}:{champions:Champion[];id:string;kind?:'icon'|'splash';art?:'draft'|'lineup';className?:string}) {
  const champion=championFor(champions,id);const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[id,kind,art]);
  return <div className={`champion-image ${className}`}>{champion&&!failed?<img loading={kind==='splash'?'eager':'lazy'} src={kind==='splash'?championArtwork(champion,art):champion.image} alt={champion.name} onError={()=>setFailed(true)}/>:<span className="champion-fallback">{champion?.name||id?.slice(0,2)||'—'}</span>}</div>;
}
export function economySource(state:BroadcastState) {
  if(state.mode==='demo')return '演示数据';
  return ({api:'客户端 API',ocr:'观战 HUD 读数',manual:'人工校准',none:'等待经济数据源'} as const)[state.economyFeed?.source||'none'];
}
export function EconomyChart({state,compact=false,interactive=false}:{state:BroadcastState;compact?:boolean;interactive?:boolean}) {
  const [hover,setHover]=useState<number|null>(null),points=state.economy.filter(p=>[p.time,p.blue,p.red].every(Number.isFinite));
  const max=Math.max(2000,...points.map(p=>Math.abs(p.blue-p.red)))*1.2,end=Math.max(1,state.gameTime,...points.map(p=>p.time)),last=points.at(-1);
  const x=(t:number)=>40+t/end*710,y=(d:number)=>105-d/max*80,segments=economySegments(points);
  const point=hover===null?undefined:points.reduce<typeof last>((nearest,p)=>!nearest||Math.abs(p.time-hover)<Math.abs(nearest.time-hover)?p:nearest,undefined);
  return <div className={`economy-chart ${compact?'compact':''}`}><svg viewBox="0 0 800 240" role="img" aria-label="双方经济差曲线，蓝色为蓝方领先，红色为红方领先，采样中断留空" onPointerMove={interactive?e=>{const rect=e.currentTarget.getBoundingClientRect();setHover(Math.max(0,Math.min(end,((e.clientX-rect.left)/rect.width*800-40)/710*end)));}:undefined} onPointerLeave={()=>setHover(null)}>{[25,65,105,145,185].map((line,i)=><g key={line}><line x1="40" x2="755" y1={line} y2={line} stroke="currentColor" strokeOpacity={i===2?'.4':'.12'} strokeDasharray={i===2?'0':'3 5'}/><text x="3" y={line+4} fill="currentColor" opacity=".8" fontSize="13">{i===2?'0':`${i<2?'+':'−'}${Math.round(max*(Math.abs(2-i)/2)/1000)}k`}</text></g>)}{segments.map((segment,i)=>{const color=segment.side==='blue'?'var(--cast-blue, #36a9e7)':'var(--cast-red, #eb5264)';return <g key={i}><polygon points={`${x(segment.from.time)},105 ${x(segment.from.time)},${y(segment.from.blue-segment.from.red)} ${x(segment.to.time)},${y(segment.to.blue-segment.to.red)} ${x(segment.to.time)},105`} fill={color} opacity=".14"/><line x1={x(segment.from.time)} y1={y(segment.from.blue-segment.from.red)} x2={x(segment.to.time)} y2={y(segment.to.blue-segment.to.red)} stroke={color} strokeWidth="3"/></g>;})}{points.length===1&&<circle cx={x(points[0].time)} cy={y(points[0].blue-points[0].red)} r="4" fill="#83d4d5"/>}{[0,.25,.5,.75,1].map(t=><text key={t} x={x(end*t)} y="221" textAnchor="middle" fill="currentColor" opacity=".8" fontSize="13">{time(end*t)}</text>)}{interactive&&state.events.filter(e=>/dragon|baron|tower|herald/i.test(e.type)).slice(-30).map(e=><circle key={e.id} cx={x(e.time)} cy="198" r="4" fill={e.team==='red'?'#ed8390':'#8bcfef'}><title>{time(e.time)} · {e.text}</title></circle>)}{point&&<line x1={x(point.time)} x2={x(point.time)} y1="20" y2="190" stroke="#eff5de" strokeDasharray="3 3"/>}</svg>{point&&<div className="chart-tooltip">{time(point.time)} · 蓝 {point.blue.toLocaleString()} / 红 {point.red.toLocaleString()} · 差 {point.blue-point.red}</div>}{!points.length&&<div className="chart-unavailable">经济曲线等待数据</div>}{points.length===1&&<div className="chart-one-point">已采集 1 个点，等待后续采样</div>}<div className="chart-sample-note">{last?`最新样本 ${time(last.time)} · ${interactive?'中断超过 30 秒或时间回退时断开曲线':'空白区间暂无连续采样'}`:'尚无有效样本'}</div></div>;
}
function TeamMark({team,className=''}:{team?:Team;className?:string}) {const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[team?.logo]);return <span className={`cast-team-mark ${className}`} title={team?.name}>{team?.logo&&!failed?<img src={team.logo} onError={()=>setFailed(true)} alt={`${team.name} 队标`}/>:<b>{team?.tag?.slice(0,1)||'?'}</b>}</span>;}
function Portrait({url,name,id,champions}:{url?:string;name?:string;id:string;champions:Champion[]}) {const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[url]);return url&&!failed?<img src={url} alt={`${name||'首发'} 选手照片`} onError={()=>setFailed(true)}/>:<ChampionImage champions={champions} id={id} kind="splash" art="lineup"/>;}
function TournamentMark({state,small=false}:{state:BroadcastState;small?:boolean}) {return <div className={`cast-tournament ${small?'small':''}`} title={state.match.title}><svg className="cast-emblem" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 2 22 8v8l-10 6L2 16V8L12 2Z" stroke="currentColor" strokeWidth="1.6"/><path d="m7 8 5-3 5 3-5 3-5-3Zm0 4 5 3 5-3M12 11v8" stroke="currentColor" strokeWidth="1.6" strokeLinejoin="round"/></svg><div><b>RIFTCAST <span>/ ARENA</span></b><small>LEAGUE OF LEGENDS · MATCH BROADCAST</small></div></div>;}
const roleNames=['TOP','JUNGLE','MID','BOT','SUPPORT'];
function sidePlayers(state:BroadcastState,side:Side) {return state.players.filter(p=>p.team===side).sort((a,b)=>{const roles=['上单','打野','中单','下路','辅助'];return (roles.indexOf(a.role)<0?5:roles.indexOf(a.role))-(roles.indexOf(b.role)<0?5:roles.indexOf(b.role));}).slice(0,5);}
function teamKills(state:BroadcastState,side:Side) {const players=sidePlayers(state,side);return state.mode==='live'&&(!players.length||players.some(p=>p.statsAvailable===false))?'—':state.stats[side].kills;}
function portraitFor(state:BroadcastState,player:Player|undefined,side:Side,index:number) {return player?.portrait||getTeam(state,side)?.players.find(p=>p.name===player?.name)?.portrait||(player?.role&&player.role!=='待分路'?getTeam(state,side)?.players.find(p=>p.role===player.role)?.portrait:undefined);}
function Equipment({player,items,version}:{player?:Player;items:ItemAssets;version:string}) {const slots=player?.itemSlots||player?.items||[];return <div className="cast-equipment">{Array.from({length:7},(_,i)=>{const id=slots[i]||0;const src=items[id]?.image||dataDragonItemImage(version,id);return <span key={i} className={i===6?'cast-trinket':''} title={id?(items[id]?.name||'装备图标加载中'):i===6?'空饰品栏':'空装备栏'}>{src?<img src={src} alt={items[id]?.name||(i===6?'饰品':'装备')} onError={e=>{e.currentTarget.style.visibility='hidden';}}/>:null}</span>;})}</div>;}
function ObserverRow({player,champions,side,items,version}:{player?:Player;champions:Champion[];side:Side;items:ItemAssets;version:string}) {
  return <div className={`cast-observer-row ${side}`}><Equipment player={player} items={items} version={version}/><span className="cast-observer-cs">{playerCs(player)}</span><ChampionImage champions={champions} id={player?.championId||''}/><span className="cast-observer-id"><strong>{player?.name||'等待选手'}</strong><small>LV {player?.level||'—'}</small><PlayerVitals player={player}/></span><b>{playerKda(player,true)}</b></div>;
}
function ObserverTable({state,champions,items,version}:{state:BroadcastState;champions:Champion[];items:ItemAssets;version:string}) {
  const blue=sidePlayers(state,'blue'),red=sidePlayers(state,'red');
  return <div className="cast-observer-table" aria-label="十名选手装备与数据"><header><span>{getTeam(state,'blue')?.tag} · ITEMS / CS / KDA</span><b>GAME {state.match.game}</b><span>KDA / CS / ITEMS · {getTeam(state,'red')?.tag}</span></header>{Array.from({length:5},(_,i)=><div className="cast-observer-pair" key={i}><ObserverRow player={blue[i]} champions={champions} side="blue" items={items} version={version}/><span className="cast-observer-role">{blue[i]?.role&&blue[i].role===red[i]?.role&&!['','待分路'].includes(blue[i].role)?['T','J','M','B','S'][['上单','打野','中单','下路','辅助'].indexOf(blue[i].role)]||'?':'?'}</span><ObserverRow player={red[i]} champions={champions} side="red" items={items} version={version}/></div>)}</div>;
}
function CapturePreview({scene}:{scene:Scene}) {return <div className={`cast-capture-preview capture-${scene}`}><div className="cast-feed-symbol" aria-hidden="true"><span/><span/><span/><span/></div><span>{scene==='draft'?'选手 / 舞台画面':scene==='interview'?'赛后采访画面':scene==='teamfight'?'游戏原生团战视角':'游戏观战画面'}</span><small>{scene==='teamfight'?'切入团战后，在游戏观战窗口按 A 切换原生视角':'RIFTCAST ARENA / 在连接与输出查看合成画面'}</small></div>;}
function BanStrip({state,champions,side}:{state:BroadcastState;champions:Champion[];side:Side}) {
 const ids=state.draft[side==='blue'?'blueBans':'redBans'],teamId=state.match[`${side}TeamId`];
 const history=(state.draftHistory||[]).filter(g=>g.seriesId===state.match.seriesId&&g.game<state.match.game&&(g.blueTeamId===teamId||g.redTeamId===teamId));
 const slots=Math.min(4,Math.max(0,Number(state.match.format.replace('BO',''))-1));
 return <div className={`cast-ban-history ${side}`} aria-label={`${side==='blue'?'蓝':'红'}方全局 BP 历史`}>{Array.from({length:slots},(_,i)=>{const game=i+1,record=history.find(g=>g.game===game),picks=record?(record.blueTeamId===teamId?record.bluePicks:record.redPicks):[];return <div className={`cast-history-game ${record?'':'is-pending'} ${state.production?.rules.mode==='standard'?'is-standard':''}`} key={game}><span>GAME {game} · {record?state.production?.rules.mode==='standard'?'已用英雄':'已选禁用':game===state.match.game?'本局':game>state.match.game?'待进行':'未归档'}</span><div>{Array.from({length:5},(_,j)=><ChampionImage key={j} champions={champions} id={picks[j]||''}/>)}</div></div>;})}<div className={`cast-bans ${side}`}><span>GAME {state.match.game} · BANS</span><div>{Array.from({length:5},(_,i)=><ChampionImage key={i} champions={champions} id={ids[i]||''}/>)}</div></div></div>;
}
function DraftCards({state,champions,side}:{state:BroadcastState;champions:Champion[];side:Side}) {
 const team=getTeam(state,side),picks=state.draft[side==='blue'?'bluePicks':'redPicks'];const assigned=(id:string)=>(state.draft.locked||state.production?.assignments.some(a=>a.locked&&a.championId===id))?state.players.find(p=>p.team===side&&p.championId===id&&p.role!=='待分路'):undefined;
 return <div className={`cast-draft-team ${side}`}><BanStrip state={state} champions={champions} side={side}/>{!!state.draft[`${side}Preselect`]?.length&&<div className="cast-draft-preselect">预选 · 未锁定：{state.draft[`${side}Preselect`]!.map(id=>championFor(champions,id)?.name??id).join(' / ')}</div>}<div className="cast-draft-cards">{Array.from({length:5},(_,i)=><div className={`cast-draft-card ${picks[i]?'locked':'waiting'} ${!picks[i]&&state.draft.activeTeam===side&&i===picks.filter(Boolean).length?'active-slot':''}`} key={i}><ChampionImage champions={champions} id={picks[i]||''} kind="splash"/><small className="cast-pick-order">{side==='blue'?'B':'R'}{i+1}</small><span className="cast-draft-role">{assigned(picks[i])?.role||'归属待确认'}</span><strong className="cast-draft-player">{assigned(picks[i])?.name||`${side==='blue'?'B':'R'}${i+1} · 选择顺序`}</strong><span className="cast-draft-champion">{championFor(champions,picks[i])?.name||'等待选择'}</span></div>)}</div></div>;
}
function DraftOverlay({state,champions}:{state:BroadcastState;champions:Champion[]}) {const blue=getTeam(state,'blue'),red=getTeam(state,'red');return <div className="cast-draft"><DraftCards state={state} champions={champions} side="blue"/><div className="cast-draft-center"><TournamentMark state={state} small/><div className="cast-draft-versus"><b>{blue?.tag}</b><span>{state.match.blueScore} : {state.match.redScore}</span><b>{red?.tag}</b></div><div className={`cast-draft-timer ${state.draft.activeTeam}`}><strong>{Math.ceil(state.draft.timer)}</strong><small>{state.draft.activeTeam==='blue'?blue?.tag:red?.tag} · {state.draft.action?.includes('等待')?'等待 BP':state.draft.action||'选人'}</small></div><small className="cast-draft-game">{state.match.format} / GAME {state.match.game}</small></div><DraftCards state={state} champions={champions} side="red"/></div>;}
function GraphicHeader({state,title,eyebrow}:{state:BroadcastState;title:string;eyebrow:string}) {return <header className="cast-graphic-header"><TournamentMark state={state}/><div><small>{eyebrow}</small><strong>{title}</strong></div><span>{state.match.format} · GAME {state.match.game}</span></header>;}
function Standby({state,now}:{state:BroadcastState;now:number}) {const blue=getTeam(state,'blue'),red=getTeam(state,'red');return <div className="cast-standby"><GraphicHeader state={state} title={state.match.title} eyebrow="MATCH DAY"/><div className="cast-opener-type" aria-hidden="true">GAME<br/>ON.</div><div className="cast-standby-match"><div className="blue"><TeamMark team={blue}/><strong>{blue?.tag}</strong><span>{blue?.name}</span></div><div className="cast-standby-versus"><small>{state.match.subtitle}</small><strong>VS</strong><span>{state.match.blueScore} — {state.match.redScore}</span></div><div className="red"><TeamMark team={red}/><strong>{red?.tag}</strong><span>{red?.name}</span></div></div><div className="cast-countdown"><span>比赛即将开始 / STARTING SOON</span><strong className={!state.overlay.countdownEnd||state.overlay.countdownEnd<=now?'countdown-message':''}>{!state.overlay.countdownEnd?'比赛即将开始':state.overlay.countdownEnd<=now?'等待比赛开始':time((state.overlay.countdownEnd-now)/1000)}</strong><small>{state.match.format} · GAME {state.match.game}</small></div><div className="cast-opener-bottom"><span>{state.match.title}</span><b>PRE MATCH</b><span>{state.mode==='demo'?'演示对局':'本地赛事转播'}</span></div></div>;}
function Lineup({state,champions}:{state:BroadcastState;champions:Champion[]}) {return <div className="cast-lineup"><GraphicHeader state={state} title="首发阵容与对位" eyebrow="STARTING LINEUP"/><div className="cast-lineup-sides">{(['blue','red'] as Side[]).map(side=>{const team=getTeam(state,side),players=sidePlayers(state,side),picks=state.draft[side==='blue'?'bluePicks':'redPicks'];return <section className={`cast-lineup-side ${side}`} key={side}><h2><TeamMark team={team}/><strong>{team?.tag}</strong><span>{team?.name}</span></h2><div className="cast-lineup-five">{Array.from({length:5},(_,i)=>{const p=players[i],photo=portraitFor(state,p,side,i),id=p?.championId||'';return <article key={i}><div className="cast-lineup-photo"><Portrait url={photo} name={p?.name||team?.players[i]?.name} id={id} champions={champions}/><span>{p?.role&&p.role!=='待分路'?p.role:'分路待确认'}</span></div><strong>{p?.name||'待确认选手'}</strong><small>{championFor(champions,id)?.name||'英雄待定'}</small></article>;})}</div></section>;})}</div><footer className="cast-lineup-bottom"><b>{getTeam(state,'blue')?.tag}</b><span>{state.match.blueScore} — {state.match.redScore}<small>{state.match.format} · GAME {state.match.game}</small></span><b>{getTeam(state,'red')?.tag}</b></footer></div>;}
function EconomyOverlay({state}:{state:BroadcastState}) {const blue=getTeam(state,'blue'),red=getTeam(state,'red'),delta=state.stats.blue.gold!=null&&state.stats.red.gold!=null?state.stats.blue.gold-state.stats.red.gold:null;return <div className="cast-analysis cast-economy"><header><span>GOLD DIFFERENCE</span><strong>团队经济走势</strong><b><GameTime state={state}/></b></header><div className="cast-economy-values"><span className="blue">{blue?.tag} <b>{gold(state.stats.blue.gold)}</b></span><strong>{delta!=null?`${delta>=0?'+':''}${gold(delta)}`:'—'}</strong><span className="red"><b>{gold(state.stats.red.gold)}</b> {red?.tag}</span></div><EconomyChart state={state}/><footer><span>来源：{economySource(state)}</span><small>{state.economyFeed?.source==='ocr'?'按观战 HUD 显示精度采样':state.economyFeed?.source==='manual'?'按导播人工输入采样':'BLUE LEAD ↑ / RED LEAD ↓'}</small></footer></div>;}
function Performance({state,champions,items,version}:{state:BroadcastState;champions:Champion[];items:ItemAssets;version:string}) {const players=[...state.players].sort((a,b)=>a.statsAvailable===false?(b.statsAvailable===false?0:1):b.statsAvailable===false?-1:(b.kills+b.assists)/Math.max(1,b.deaths)-(a.kills+a.assists)/Math.max(1,a.deaths)).slice(0,10);return <div className="cast-analysis cast-performance"><header><span>PLAYER PERFORMANCE</span><strong>{currentGameResult(state)?`第 ${state.match.game} 局${gameResultAwaitingTerminalSample(currentGameResult(state))?'已保存':'最终'}选手数据`:'选手数据 / KDA 排序'}</strong><b><GameTime state={state}/></b></header><div className="cast-performance-head"><span>选手 / 英雄</span><span>K / D / A</span><span>CS</span><span>LV</span><span>个人经济</span><span>装备</span></div>{players.map((p,i)=><div className={`cast-performance-row ${p.team}`} key={p.id}><span><em>{p.statsAvailable===false?'—':String(i+1).padStart(2,'0')}</em><ChampionImage champions={champions} id={p.championId}/><strong>{p.name}</strong></span><b>{playerKda(p)}</b><span>{playerCs(p)}</span><span>{p.level}</span><span>{gold(p.gold)}</span><Equipment player={p} items={items} version={version}/></div>)}<footer>个人累计经济来自客户端累计字段或原生观战金币列 · 装备栏独立显示</footer></div>;}
function Schedule({state}:{state:BroadcastState}) {const page=schedulePage(state);return <div className="cast-schedule"><GraphicHeader state={state} title="赛事赛程" eyebrow="MATCH SCHEDULE"/><div className="cast-schedule-heading"><strong>MATCH<br/>SCHEDULE</strong><span>{state.match.title}<small>所有时间为北京时间</small></span></div><div className="cast-schedule-list">{page.matches.map((m,i)=>{const blue=state.teams.find(t=>t.id===m.blueTeamId),red=state.teams.find(t=>t.id===m.redTeamId);return <div className={`cast-schedule-row ${m.status}`} key={m.id}><small>{String(page.index*4+i+1).padStart(2,'0')}</small><time>{new Date(m.scheduledAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}</time><span><TeamMark team={blue}/><b>{blue?.tag||'TBD'}</b></span><strong>{m.status==='scheduled'?'VS':`${m.blueScore} : ${m.redScore}`}</strong><span><b>{red?.tag||'TBD'}</b><TeamMark team={red}/></span><em>{m.status==='live'?'进行中':m.status==='finished'?'已结束':`未开赛 · ${m.format}`}</em></div>;})}{!page.matches.length&&<p className="cast-empty">赛程待公布</p>}</div><footer className="cast-schedule-pagination">第 {page.index+1} / {page.pages} 页 · 共 {page.total} 场</footer></div>;}
function Postgame({state,champions,items,version}:{state:BroadcastState;champions:Champion[];items:ItemAssets;version:string}) {const blue=getTeam(state,'blue'),red=getTeam(state,'red');return <div className="cast-postgame"><GraphicHeader state={state} title={currentGameResult(state)?`第 ${state.match.game} 局赛后数据报告 · ${gameResultAwaitingTerminalSample(currentGameResult(state))?'等待终局样本':currentGameResult(state)?.terminalSampleComplete===false?'观测值含缺失':'已冻结'}`:'赛后数据报告'} eyebrow="POST GAME REPORT"/><div className="cast-result"><div className="blue"><TeamMark team={blue}/><strong>{blue?.tag}</strong></div><span>{currentGameResult(state)?.winner&&<strong className="cast-winner">本局胜方 · {getTeam(state,currentGameResult(state)!.winner!)?.name}</strong>}<b>{state.match.blueScore} — {state.match.redScore}</b><small>系列赛比分 · {state.match.format} · GAME {state.match.game}</small><em>对局时长 <GameTime state={state}/></em></span><div className="red"><strong>{red?.tag}</strong><TeamMark team={red}/></div></div><div className="cast-team-comparison">{[['击杀',teamKills(state,'blue'),teamKills(state,'red')],['团队经济',gold(state.stats.blue.gold),gold(state.stats.red.gold)],['防御塔',state.stats.blue.objectivesAvailable===false?'—':state.stats.blue.towers,state.stats.red.objectivesAvailable===false?'—':state.stats.red.towers],['小龙',state.stats.blue.objectivesAvailable===false?'—':state.stats.blue.dragons,state.stats.red.objectivesAvailable===false?'—':state.stats.red.dragons],['大龙',state.stats.blue.objectivesAvailable===false?'—':state.stats.blue.barons,state.stats.red.objectivesAvailable===false?'—':state.stats.red.barons]].map(([label,b,r])=><div key={label}><b className="blue">{b}</b><span>{label}</span><b className="red">{r}</b></div>)}</div><div className="cast-report-teams">{(['blue','red'] as Side[]).map(side=><section className={side} key={side}><header><span>PLAYER / CHAMPION</span><span>K / D / A</span><span>CS</span><span>GOLD</span></header>{sidePlayers(state,side).map(p=><div key={p.id}><span><ChampionImage champions={champions} id={p.championId}/><strong>{p.name}</strong><Equipment player={p} items={items} version={version}/></span><b>{playerKda(p)}</b><span>{playerCs(p)}</span><span>{gold(p.gold)}</span></div>)}</section>)}</div><footer><span>团队经济来源：{economySource(state)}</span><span>{state.match.title}</span><span>{state.mode==='demo'?'DEMO DATA':'LOCAL MATCH DATA'}</span></footer></div>;}
function Interview({state}:{state:BroadcastState}) {const player=state.players.find(p=>p.id===state.selectedPlayerId),team=player?getTeam(state,player.team):undefined,info=state.overlay.interview;return <div className={`cast-interview dock-${info?.dock??'left'}`}><TournamentMark state={state} small/><span className="cast-interview-name"><small>{info?.topic||'POST MATCH INTERVIEW / 赛后采访'}</small><strong>{info?info.name||'赛后采访':player?.name||'赛后采访'}</strong><span>{info?[info.team,info.role].filter(Boolean).join(' · '):team?.name||state.match.title}</span></span><b>{state.match.format}<small>GAME {state.match.game}</small></b></div>;}
export function BroadcastCanvas({state:sourceState,champions,scene,output=false,bus='preview'}:{state:BroadcastState;champions:Champion[];scene:Scene;output?:boolean;bus?:'program'|'preview'}) {
 const frozenResult=bus!=='program'&&['ranking','postgame'].includes(scene)?currentGameResult(sourceState)||reportGameResult(sourceState):undefined;
 const state=frozenResult?frozenGameState(sourceState,frozenResult):sourceState;
 const [now,setNow]=useState(Date.now());const {version,items}=useItemCatalog(scene==='teamfight'?[]:champions,state.production?.versions.resources);
 useEffect(()=>{if(scene!=='standby'&&scene!=='live')return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[scene]);
 // The game's A view supplies the teamfight HUD. Keep the OBS layer fully transparent.
 if(scene==='teamfight')return <div className={`broadcast-container cast-container skin-arena ${output?'is-output':''}`}><div className="broadcast-canvas cast-canvas cast-scene-teamfight transparent cast-transparent" aria-label="游戏原生团战视角">{!output&&<CapturePreview scene={scene}/>}</div></div>;
 const liveScene=['live','gold-ranking','economy','ranking'].includes(scene);
 const overlayScene=['draft','live','gold-ranking','economy','ranking','interview'].includes(scene),selected=state.players.some(p=>p.id===state.selectedPlayerId);
 const feed=scene==='draft'||scene==='lineup'?state.connections.lcu:state.connections.live;
 const sourceIssue=!frozenResult&&state.mode==='live'&&['live','teamfight','gold-ranking','draft','lineup','economy','ranking'].includes(scene)&&feed.status!=='connected';
 return <div className={`broadcast-container cast-container skin-arena ${output?'is-output':''}`} style={{'--broadcast-accent':state.overlay.accent} as CSSProperties}><div className={`broadcast-canvas cast-canvas cast-scene-${scene} ${state.overlay.ticker?'has-ticker':''} ${overlayScene&&output?'transparent cast-transparent':''}`} style={{'--hud-scale':state.overlay.scale} as CSSProperties}>
 {overlayScene&&!output&&<CapturePreview scene={scene}/>}
 {liveScene&&<NativeHudLayer state={state}/>}
 {scene==='live'&&<LiveBottom state={state} champions={champions} items={items} version={version}/>}
 {scene==='standby'&&<Standby state={state} now={now}/>}
 {scene==='draft'&&<DraftOverlay state={state} champions={champions}/>}
 {scene==='lineup'&&<Lineup state={state} champions={champions}/>}
 {liveScene&&state.overlay.scoreboard&&<LiveTop state={state}/>}
 {scene==='gold-ranking'&&<GoldRankingOverlay state={state} champions={champions}/>}
 {scene==='economy'&&<EconomyOverlay state={state}/>}
 {scene==='ranking'&&(selected?<PlayerBuild state={state} champions={champions} output/>:<Performance state={state} champions={champions} items={items} version={version}/>)}
 {scene==='schedule'&&<Schedule state={state}/>}
 {scene==='postgame'&&<Postgame state={state} champions={champions} items={items} version={version}/>}
 {scene==='interview'&&<Interview state={state}/>}
 {(state.overlay.sponsor||state.overlay.sponsorLogo)&&<div className="cast-sponsor">{state.overlay.sponsorLogo?<img src={state.overlay.sponsorLogo} alt={state.overlay.sponsor||'赞助商标志'}/>:<span>{state.overlay.sponsor}</span>}</div>}
 {state.overlay.ticker&&<div className="cast-ticker"><b>{state.match.title}</b><span>{state.overlay.tickerText}</span></div>}
 {state.mode==='demo'&&<span className="cast-demo">DEMO · 演示数据</span>}
 {sourceIssue&&<div className="cast-source-status">{feed.updatedAt?'比赛数据暂不可用':'等待比赛数据'}{feed.updatedAt&&<span> · 截至 {new Date(feed.updatedAt).toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})}</span>}</div>}
 </div></div>;
}
