import { useEffect, useRef, useState } from 'react';
import type { Scene, StateContext } from '../../shared/types';
import type { CheckId, ProductionCommand } from '../../shared/production-types';
import { checkValid, objectiveRemaining, dataHealth, productionKey, programState } from '../../shared/production';
import { api, getTeam, sceneInfo, time } from '../lib';
import './production-desk.css';

type AudioBus = { name: string; available: boolean; db?: number; muted?: boolean; peakDb?: number; meterAvailable?: boolean; silentSeconds?: number; monitor?: string; syncOffset?: number };
type ProductionStatus = { audio: AudioBus[]; disk: { directory?: string; freeBytes?: number; detail: string }; recording: { outputActive: boolean; outputDuration: number } | null; bufferActive: boolean | null; emergencyAvailable: boolean; gameSource: string };
type EngineHealth = { connected: boolean; selection?: { gameWindow: string; micEnabled: boolean }; performance?: { activeFps: number; sampleSeconds: number; rendering: { percent: number }; encoding: { percent: number }; network: { percent: number; bitrateKbps: number; reconnecting: boolean; reconnectingSeconds?:number }; issues: string[] } };
const checks: [CheckId, string][] = [['identity', '比赛身份与十人名单'], ['game', '正确游戏窗口与采集区'], ['data', '数据样本匹配本局'], ['audio', '30 秒试录与声音回看'], ['disk', '录制路径与磁盘空间'], ['program', '节目内容与音画同步'], ['platform', '平台接收端人工回看']];

export function ProductionBar({ state, send, notify }: StateContext) {
  const p = state.production, pgm = programState(state), pending = p?.program?.version !== p?.configVersion;
  const run = (command: ProductionCommand) => void send({ type: 'production', command }).catch(() => {});
  const engine = async (action: string) => { try { await api('/api/obs/production', { method: 'POST', body: JSON.stringify({ action }) }); notify('OBS 已确认操作'); } catch (e) { notify(e instanceof Error ? e.message : '操作未完成'); } };
  return <section className="production-bar" aria-label="固定播出与应急控制">
    <div><strong>PGM · {p?.playingClipId?'独立回放':sceneInfo[state.programScene].name}</strong><small>{getTeam(pgm,'blue')?.tag} {pgm.match.blueScore}:{pgm.match.redScore} {getTeam(pgm,'red')?.tag} · G{pgm.match.game} · 已播 v{p?.program?.version ?? 1}</small></div>
    <div><strong>PVW · {sceneInfo[state.previewScene].name}</strong><small>待播 v{p?.configVersion ?? 1}{pending ? ' · 有待应用修改' : ' · 配置一致'}</small></div>
    <button className="button primary small" onClick={() => void send({ type: 'take' }).catch(() => {})}>整体切入</button>
    <button className="button small" onClick={() => void engine('return-live')}>回到比赛</button>
    <button className="button small" onClick={() => run({ op: 'immediate', action: 'analysis-off' })}>关闭分析</button>
    <button className="button small" onClick={() => run({ op: 'immediate', action: 'feeds-off' })}>关闭选手画面</button>
    <button className="button small danger" onClick={() => void engine('emergency')}>技术暂停</button>
    <button className="button small" disabled={!p?.previousProgram} onClick={() => run({ op: 'immediate', action: 'undo' })}>撤回切换</button>
    <small className="production-native-hint">游戏前台备用：Ctrl+Alt+Shift+P · OBS 本地画面</small>
  </section>;
}

export function ProductionDesk(ctx: StateContext) {
  const { state, send, notify } = ctx, p = state.production;
  const [status, setStatus] = useState<ProductionStatus | null>(null), [engine, setEngine] = useState<EngineHealth | null>(null);
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), [note, setNote] = useState('');
  const [subtitle, setSubtitle] = useState(''), [rundownScene, setRundownScene] = useState<Scene>('live');
  const [resourceStatus, setResourceStatus] = useState(''), [resultId, setResultId] = useState('');
  const [inviteRole,setInviteRole]=useState('data'),[inviteUrl,setInviteUrl]=useState('');
  const local = ['localhost','127.0.0.1','[::1]'].includes(location.hostname);
  const active = useRef(false);
  useEffect(() => {
    if (!local || state.connections.obs.status !== 'connected') { setStatus(null); setEngine(null); return; }
    let stopped = false, fetching = false;
    const refresh = async () => { if (fetching || document.hidden || active.current) return; fetching = true;
      const [prod, health] = await Promise.allSettled([api<ProductionStatus>('/api/obs/production'), api<EngineHealth>('/api/obs/engine')]);
      if (!stopped) { if (prod.status === 'fulfilled') setStatus(prod.value); if (health.status === 'fulfilled') setEngine(health.value); }
      fetching = false;
    }; void refresh(); const timer = setInterval(() => void refresh(), 3000); return () => { stopped = true; clearInterval(timer); };
  }, [local, state.connections.obs.status]);
  if (!p) return null;
  const run = async (work: () => Promise<unknown>, success = '') => { if (active.current) return; active.current = true; setBusy(true); setError(''); try { await work(); if (success) notify(success); } catch (e) { setError(e instanceof Error ? e.message : '操作未完成'); } finally { active.current = false; setBusy(false); } };
  const command = (c: ProductionCommand, message = '') => void run(() => send({ type: 'production', command: c }), message);
  const obs = (data: Record<string, unknown>) => void run(async () => { setStatus(await api<ProductionStatus>('/api/obs/production', { method: 'POST', body: JSON.stringify(data) })); }, '制作操作已确认');
  const health = dataHealth(state), perf = engine?.performance, currentKey = productionKey(state), clipKey=productionKey(programState(state)), result = state.gameResults?.find(r => r.id === resultId) ?? state.gameResults?.filter(r => r.seriesId === state.match.seriesId).at(-1);
  const needsReason = !note.trim();
  const recent=state.events.filter(e=>state.gameTime-e.time>=0&&state.gameTime-e.time<=30&&/kill|dragon|baron|tower|herald/i.test(e.type)).slice(-2);
  const lastMark=p.marks.filter(m=>m.key===currentKey).at(-1),difference=state.stats.blue.gold!==null&&state.stats.red.gold!==null?state.stats.blue.gold-state.stats.red.gold:null;
  const economyHint=difference!==null&&(state.mode==='demo'||state.economyFeed?.status==='fresh')?`${getTeam(state,difference>=0?'blue':'red')?.tag??''} 累计经济领先 ${Math.abs(Math.round(difference))}`:'经济等待有效采样';
  return <section className="production-desk" aria-label="比赛日制作控制">
    <div className="production-summary">
      <span>{state.mode === 'demo' ? '演示模式 · 正式播出前切换并核对' : '本地实况'} · {p.entry === 'bp' ? 'BP 准备' : p.entry === 'loading' ? '加载中' : p.entry === 'waiting' ? '等待游戏信号' : p.entry === 'verify' ? '进局核对' : '已播局内'} · 尝试 {p.attempt}</span>
      <span>KDA/CS {health.stats}/{health.total} · 累计经济 {health.gold}/{health.total} · 分路 {health.roles}/{health.total}{health.teamAge !== null ? ` · 团队采样 ${(health.teamAge/1000).toFixed(1)}s` : ''}</span>
      <span className={p.application?.status === 'failed' || p.persistence?.status === 'failed' ? 'red-text' : ''}>来源：{p.application?.detail ?? '等待切入'} · 保存：{p.persistence?.status === 'saved' ? '已写入磁盘' : p.persistence?.status === 'failed' ? '保存失败' : '待保存'}</span>
      <button className="button small" disabled={busy || p.application?.status !== 'applied'} onClick={() => command({ op: 'confirm-picture' })}>确认节目画面</button>
    </div>
    {error && <p role="alert" className="production-error">{error}</p>}
    <div className="production-health" aria-label="输出健康">
      <span>OBS {engine?.connected ? '已连接' : '待连接'}</span><span>游戏源 {engine?.selection?.gameWindow ? '已选择 · 画面需核对' : '待选择'}</span>
      <span>渲染 {perf ? `${perf.activeFps.toFixed(1)} fps / 丢帧 ${perf.rendering.percent.toFixed(2)}%` : '待确认'}</span><span>编码 {perf ? `${perf.encoding.percent.toFixed(2)}%` : '待确认'}</span>
      <span>发送 {perf ? `${Math.round(perf.network.bitrateKbps)} kbps / ${perf.network.percent.toFixed(2)}%${perf.network.reconnecting ? ` · 重连 ${time(perf.network.reconnectingSeconds??0)}` : ''}` : '待确认'}</span>
      <span>平台 {checkValid(state,'platform') ? '已人工回看' : '待回看'}</span><span>录制 {status?.recording?.outputActive ? time(status.recording.outputDuration/1000) : '未录制 / 待确认'}</span>
      <span>磁盘 {status?.disk.freeBytes !== undefined ? `${(status.disk.freeBytes/1024**3).toFixed(1)} GB 可用` : '待核对'}</span>
      <span>统计窗口 {perf ? `${perf.sampleSeconds.toFixed(1)}s` : '待采样'}</span>
      {status?.audio.slice(0,2).map(bus=><span key={bus.name}>{bus.name.replace('RiftCast ','')} · {bus.muted?'已静音':bus.meterAvailable?`${bus.peakDb?.toFixed(1)} dB`:'电平待确认'}</span>)}
    </div>
    {p.alerts?.some(a=>!a.resolvedAt)&&<div className="production-error" aria-label="制作告警">{p.alerts.filter(a=>!a.resolvedAt).map(a=><p key={a.id}>{a.text} · {a.acknowledgedAt?'已确认，等待恢复':new Date(a.at).toLocaleTimeString('zh-CN')} <button className="button small" disabled={!!a.acknowledgedAt||busy} onClick={()=>command({op:'ack-alert',id:a.id})}>确认告警</button></p>)}</div>}
    <div className="production-summary" aria-label="建议关注"><span>建议关注 · {economyHint}</span>{recent.map(e=><span key={e.id}>{time(e.time)} · {e.text}</span>)}{lastMark&&<span>人工提示 · {lastMark.text}</span>}<small>先观察小地图、兵线与站位；事件提示不会自动改变镜头。</small></div>
    <details><summary>音频台 · 游戏、解说、采访、音乐、回放</summary><p className="muted">监听请使用独立耳机设备，避免返送被桌面音频重复采集。设备与编码设置在停播窗口修改。</p>
      <div className="production-audio">{(status?.audio ?? ['RiftCast 桌面音频','RiftCast 解说麦克风','RiftCast 采访','RiftCast 音乐','RiftCast 回放片段'].map(name=>({name,available:false} as AudioBus))).map(bus => <div key={bus.name}>
        <strong>{bus.name.replace('RiftCast ','')}</strong><span>{!bus.available ? '来源待接入' : !bus.meterAvailable ? '电平待采样' : `${bus.peakDb!.toFixed(1)} dB${bus.peakDb! > -1 ? ' · 接近削波' : ''}`}</span>
        <meter min={-60} max={0} value={bus.peakDb ?? -60} aria-label={`${bus.name} 电平`}/>
        <input type="range" aria-label={`${bus.name} 音量`} min={-60} max={6} defaultValue={bus.db ?? 0} key={`${bus.name}-${bus.db}`} disabled={!bus.available||busy} onPointerUp={e=>obs({action:'audio',name:bus.name,db:Number(e.currentTarget.value)})} onKeyUp={e=>obs({action:'audio',name:bus.name,db:Number(e.currentTarget.value)})}/>
        <button className="button small" disabled={!bus.available||busy} onClick={()=>obs({action:'audio',name:bus.name,muted:!bus.muted})}>{bus.muted ? '取消静音' : '静音'}</button>
        <select aria-label={`${bus.name} 监听`} disabled={!bus.available||busy} value={bus.monitor ?? 'OBS_MONITORING_TYPE_NONE'} onChange={e=>obs({action:'audio',name:bus.name,monitor:e.target.value})}><option value="OBS_MONITORING_TYPE_NONE">关闭监听</option><option value="OBS_MONITORING_TYPE_MONITOR_ONLY">仅监听</option><option value="OBS_MONITORING_TYPE_MONITOR_AND_OUTPUT">监听并送节目</option></select>
        <input type="number" aria-label={`${bus.name} 同步偏移毫秒`} min={-10000} max={10000} defaultValue={bus.syncOffset ?? 0} disabled={!bus.available||busy} onBlur={e=>{if(Number(e.target.value)!==bus.syncOffset)obs({action:'audio',name:bus.name,syncOffset:Number(e.target.value)});}}/><small>ms</small>
      </div>)}</div><button className="button small" disabled={busy} onClick={()=>obs({action:'tracks'})}>停播配置成品 / 游戏 / 解说三轨录制</button>
    </details>
    <details><summary>比赛日检查与固定版本 · {checks.filter(([id])=>checkValid(state,id)).length}/7</summary><div className="production-checks">{checks.map(([id,label])=><div key={id}><span className={checkValid(state,id)?'green-text':''}>{checkValid(state,id)?'✓':'○'} {label}</span><small>{checkValid(state,id)?`${p.checks[id]?.actor} · ${new Date(p.checks[id]!.at).toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai'})}`:'待人工确认'}</small><button className="button small" disabled={busy} onClick={()=>command({op:'check',id,note:note||'人工核对'})}>确认</button></div>)}</div>
      <p className="muted">游戏来源或音频设备改变后，对应检查会失效；OBS 已连接仍需分别核对画面、声音和接收端。</p>
      <div className="production-form">{(['game','resources','ocr'] as const).map((key,i)=><label key={key}>{['比赛补丁','静态资源版本','OCR 布局版本'][i]}<input defaultValue={p.versions[key]} key={`${key}-${p.versions[key]}`} onBlur={e=>{if(e.target.value!==p.versions[key])command({op:'settings',versions:{...p.versions,[key]:e.target.value}});}}/></label>)}<button className="button" disabled={busy} onClick={()=>void run(async()=>{const result=await api<{detail:string}>('/api/resources/cache',{method:'POST',body:JSON.stringify({version:p.versions.resources})});setResourceStatus(result.detail);})}>停播准备离线素材</button></div><button className="button small" disabled={busy} onClick={()=>void run(async()=>{const report=await api<{detail:string;missing:string[];remote:string[]}>('/api/resources/inventory');setResourceStatus(`${report.detail}${report.missing.length?' · 缺失：'+report.missing.join(' / '):''}${report.remote.length?' · 远程图片请先上传至本机素材库':''}`);})}>检查全部素材</button><p>{resourceStatus}</p>{p.versions.game&&p.versions.game!==p.versions.resources&&<p className="muted">比赛补丁与 Data Dragon 版本标记不同，请实际核对本场资源。</p>}
      <a href="/api/archive" download>导出赛事资料、结果修订、视频与片段索引</a><p className="muted">当前局内 API、LCU 与 Replay 连接状态可在「连接与输出」核对；更新客户端后重新校准 OCR。</p>
    </details>
    <details><summary>镜头提示、分析时长与选手保持</summary><p className="muted">当前游戏捕获供节目和预监共用。镜头按键送到游戏观战窗口；工作台用于准备包装。本机键位在下方填写并经观战客户端核对。下列选手按钮用于准备选手数据包装。事件提示仅提醒导播。</p>
      <div className="production-form"><label>实际键盘控制对象<select value={p.keyboardTarget??'workbench'} onChange={e=>command({op:'settings',keyboardTarget:e.target.value as 'game'|'workbench'})}><option value="workbench">浏览器工作台</option><option value="game">游戏观战窗口 · 手动切回焦点</option></select></label><label>本机已核对的跟随 / 手动 / 迷雾键位<input defaultValue={p.cameraHints} onBlur={e=>command({op:'settings',cameraHints:e.target.value})}/></label></div>
      <div className="production-follow">{state.players.map(player=><button className="button small" key={player.id} onClick={()=>void send({type:'select-player',playerId:player.id}).catch(()=>{})}>{player.name} · {player.role}</button>)}</div>
      <div className="production-form"><label>分析播出时长 / 秒<input type="number" min={3} max={120} defaultValue={p.analysisSeconds} onBlur={e=>command({op:'settings',analysisSeconds:Number(e.target.value)})}/></label><label><input type="checkbox" checked={p.feedHold} onChange={e=>command({op:'settings',feedHold:e.target.checked})}/>保持选手画面</label><label><input type="checkbox" checked={p.dynamicPreview} onChange={e=>command({op:'settings',dynamicPreview:e.target.checked})}/>主预监原生动态显示 · HUD 30 FPS</label><label>观战布局<select value={p.layout} onChange={e=>command({op:'settings',layout:e.target.value as 'single'|'dual'})}><option value="single">单屏主控</option><option value="dual">双屏观战</option></select></label></div>
      <p>最新事件：{state.events.at(-1)?.text ?? '等待事件'} · {p.marks.filter(m=>m.key===currentKey).at(-1)?.text ?? '尚无人工提示'}</p>
      <div className="production-form"><input placeholder="危险、精彩或资源提示" value={note} onChange={e=>setNote(e.target.value)}/>{(['danger','highlight','objective'] as const).map((kind,i)=><button className="button small" key={kind} disabled={busy||needsReason} onClick={()=>command({op:'mark',text:note,kind})}>{['危险标记','标记精彩','资源标记'][i]}</button>)}</div>
      <div className="production-form"><button className="button small" disabled={busy||needsReason} onClick={()=>command({op:'objective',label:note,reason:'导播人工确认'})}>确认资源事件</button><button className="button small" disabled={busy||needsReason} onClick={()=>{const seconds=Number(prompt('本场版本已核对的刷新间隔 / 秒'));if(seconds>0)command({op:'objective',label:note,dueTime:state.gameTime+seconds,reason:'本场版本人工确认'});}}>确认资源倒计时</button></div>
      {p.objectives.filter(o=>o.key===currentKey).slice(-4).map(o=><p key={o.id}>{o.label} · {objectiveRemaining(state,o)!==null?`剩余 ${time(objectiveRemaining(state,o)!)}`:'计时待确认'} · {o.reason}</p>)}
    </details>
    <details><summary>独立回放缓冲与片段队列 · {p.clips.length} 个片段</summary><p className="muted">缓冲初始为 60 秒。片段保留录制中的原比分和时钟，OBS 回放场景关闭实时 HUD。当前游戏客户端继续向前。</p><div className="inline-buttons"><button className="button" disabled={busy||status?.bufferActive===true} onClick={()=>obs({action:'start-buffer'})}>启动缓冲</button><button className="button" disabled={busy||!status?.bufferActive} onClick={()=>obs({action:'save-clip',title:note||undefined})}>保存精彩片段</button><button className="button" disabled={busy||!status?.bufferActive} onClick={()=>obs({action:'stop-buffer'})}>停止缓冲</button><button className="button primary" disabled={busy} onClick={()=>obs({action:'return-live'})}>立即回到比赛</button></div>
      {(p.playingClipId||['economy','gold-ranking','ranking'].includes(state.programScene))&&<div className="production-current-game"><strong>当前比赛监视器 · 游戏来源</strong><LiveGameImage/><span>当前比赛 {time(state.gameTime)} · 分析与回放播出期间继续观察</span></div>}
      {p.clips.slice(0,15).map(clip=><div className="production-clip" key={clip.id}><strong>{clip.title}</strong>{clip.status!=='saved'&&!p.playingClipId&&<video controls preload="metadata" src={`/api/clips/${clip.id}/file#t=${clip.inPoint},${clip.outPoint}`} aria-label="片段画面与声音预监"/>}<small>{clip.key===clipKey?'本局':'其他局'} · {clip.status==='saved'?'已保存，待解码':clip.status==='ready'?'预监已就绪':'已播'}</small><label>入点 / 秒<input type="number" min={0} max={clip.duration} defaultValue={clip.inPoint} onBlur={e=>obs({action:'edit-clip',id:clip.id,inPoint:Number(e.target.value),outPoint:clip.outPoint,audio:clip.audio})}/></label><label>出点 / 秒<input type="number" min={clip.inPoint} max={clip.duration} defaultValue={clip.outPoint} onBlur={e=>obs({action:'edit-clip',id:clip.id,inPoint:clip.inPoint,outPoint:Number(e.target.value),audio:clip.audio})}/></label><select aria-label="回放声音组合" value={clip.audio} onChange={e=>obs({action:'edit-clip',id:clip.id,inPoint:clip.inPoint,outPoint:clip.outPoint,audio:e.target.value})}><option value="original">片段原声</option><option value="commentary">现场解说</option></select><button className="button small" disabled={busy||clip.key!==clipKey||!!p.playingClipId} onClick={()=>obs({action:'prepare-clip',id:clip.id})}>预监</button><button className="button primary small" disabled={busy||clip.status==='saved'||clip.key!==clipKey||!!p.playingClipId} onClick={()=>obs({action:'play-clip',id:clip.id})}>切入片段</button></div>)}
    </details>
    <details><summary>正式暂停、信号恢复、重赛与结果纠正</summary><input placeholder="裁判决定、暂停或纠正理由" value={note} onChange={e=>setNote(e.target.value)}/><div className="inline-buttons"><button className="button" disabled={busy||needsReason} onClick={()=>command({op:'pause',kind:'official',reason:note})}>记录正式暂停</button><button className="button" disabled={busy||needsReason} onClick={()=>command({op:'resume',reason:note})}>核对后恢复就绪</button><HoldButton disabled={busy||needsReason} onExecute={()=>command({op:'remake',reason:note})}>按住 1 秒重赛</HoldButton></div>{p.pause&&<p>{p.pause.kind==='official'?'正式暂停':p.pause.kind==='signal'?'信号故障':'录像暂停'} · {p.pause.reason} · 现实经过 {time((Date.now()-Date.parse(p.pause.at))/1000)}</p>}
      {result&&<div className="production-form"><select aria-label="纠正结果的局" value={result.id} onChange={e=>setResultId(e.target.value)}>{state.gameResults?.filter(r=>r.seriesId===state.match.seriesId).map(r=><option value={r.id} key={r.id}>GAME {r.game} · {r.winner??'待确认'}</option>)}</select><span>会重算 BO 比分、赛程和系列赛结束状态，并保留旧结果。</span>{(['blue','red'] as const).map(side=><button className="button" key={side} disabled={busy||needsReason} onClick={()=>void run(()=>send({type:'correct-result',resultId:result.id,winner:side,reason:note}),'结果已修订并保存')}>纠正为{side==='blue'?'蓝':'红'}方胜</button>)}</div>}
      <div className="production-video-index">{p.videos.slice(-10).map(v=><p key={v.id}>{v.title} · GAME {v.game} · 尝试 {v.attempt} · {v.file||'录制进行中'} · 视频 {v.startVideoSeconds?.toFixed(1)??'待确认'}–{v.endVideoSeconds?.toFixed(1)??'录制中'}s · {v.detail||'录制待结束'} {v.file&&<a href={`/api/videos/${v.id}/file`}>打开对应录像文件</a>}</p>)}</div><p className="muted">长期记录与片段索引继续保留；快捷列表显示最近项目，赛事包含全部结果与索引。快照列表最多保留 100 条，旧快照可从有效结果记录导出。</p>
    </details>
    <details><summary>待播顺序、字幕立即播出与控制席</summary><div className="production-form"><select value={rundownScene} onChange={e=>setRundownScene(e.target.value as Scene)}>{Object.entries(sceneInfo).map(([scene,info])=><option value={scene} key={scene}>{info.name}</option>)}</select><button className="button" onClick={()=>command({op:'rundown',items:[...p.rundown,{id:crypto.randomUUID(),scene:rundownScene,title:sceneInfo[rundownScene].name,seconds:15,status:'pending'}]})}>加入待播顺序</button></div>{p.rundown.map(item=><div className="production-rundown" key={item.id}><span>{item.title} · {item.seconds}s · {item.status==='aired'?'已播':item.status==='ready'?'预备':'待准备'}</span><button className="button small" onClick={()=>void run(async()=>{await send({type:'preview-scene',scene:item.scene});await send({type:'production',command:{op:'rundown',items:p.rundown.map(r=>r.id===item.id?{...r,status:'ready'}:r)}});})}>预备</button><button className="button small" onClick={()=>void run(async()=>{await send({type:'take',scene:item.scene});await send({type:'production',command:{op:'rundown',items:p.rundown.map(r=>r.id===item.id?{...r,status:'aired'}:r)}});})}>切入并标记已播</button></div>)}
      <div className="production-form"><input aria-label="抢时字幕" value={subtitle} onChange={e=>setSubtitle(e.target.value)} placeholder="临场字幕"/><button className="button" onClick={()=>command({op:'immediate',action:'ticker',text:subtitle})}>立即播出字幕</button><button className="button" onClick={()=>command({op:'immediate',action:'ticker',text:''})}>立即撤下字幕</button></div>
      <p>节目控制席：{p.control?.name??'当前主机导播'} · 制作提示仅显示在工作台。平台延迟返送与当前游戏监视器分别核对。</p><button className="button" disabled={busy||needsReason} onClick={()=>void run(()=>api('/api/control/claim',{method:'POST',body:JSON.stringify({reason:note})}),'已接管节目控制')}>凭理由接管主导播席</button>
      {local&&<div className="production-form"><label>邀请席位<select value={inviteRole} onChange={e=>setInviteRole(e.target.value)}>{[['readonly','只读'],['data','资料'],['subtitle','字幕'],['replay','回放'],['director','主导播']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><button className="button small" onClick={()=>void run(async()=>{const invite=await api<{url?:string}>('/api/control/invite',{method:'POST',body:JSON.stringify({role:inviteRole,name:note||'协作席位'})});setInviteUrl(invite.url??'先启用局域网控制，再生成移动席位邀请');})}>生成席位邀请</button>{inviteUrl&&<input aria-label="移动席位邀请链接" readOnly value={inviteUrl}/>}</div>}
      <div className="production-form">{Object.entries(p.hotkeys).map(([key,value])=><label key={key}>{({take:'切入',live:'回到比赛',analysis:'关闭分析',feeds:'关闭选手',emergency:'技术暂停',undo:'撤回'} as Record<string,string>)[key]}<input defaultValue={value} onBlur={e=>{if(e.target.value!==value)command({op:'settings',hotkeys:{...p.hotkeys,[key]:e.target.value}});}}/></label>)}</div>
    </details>
  </section>;
}

function LiveGameImage(){const [stamp,setStamp]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setStamp(Date.now()),1000);return()=>clearInterval(timer);},[]);return <img src={`/api/obs/game-frame?t=${stamp}`} alt="持续前进的当前游戏画面"/>;}
export function HoldButton({children,onExecute,disabled=false}:{children:React.ReactNode;onExecute:()=>void;disabled?:boolean}){const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),[holding,setHolding]=useState(false);const stop=()=>{clearTimeout(timer.current);setHolding(false);};useEffect(()=>()=>clearTimeout(timer.current),[]);return <button className={`button small danger ${holding?'holding':''}`} disabled={disabled} onPointerDown={e=>{if(e.button!==0)return;e.currentTarget.setPointerCapture(e.pointerId);setHolding(true);timer.current=setTimeout(()=>{stop();onExecute();},1000);}} onPointerUp={stop} onPointerCancel={stop} onKeyDown={e=>{if((e.key===' '||e.key==='Enter')&&!e.repeat){e.preventDefault();setHolding(true);timer.current=setTimeout(()=>{stop();onExecute();},1000);}}} onKeyUp={stop} onBlur={stop}>{children}</button>;}
