import { useEffect, useState } from 'react';
import { Check, RefreshCw, Search } from 'lucide-react';
import { api } from '../lib';

interface Diagnostic {status:string;detail:string;configPath?:string;configEnabled?:boolean;restartRequired:boolean;lastProbeAt:string;endpoints:{path:string;available:boolean;statusCode?:number;errorKind?:string}[];playback?:{paused:boolean;time:number;speed:number;length?:number}}
export function ReplayDiagnostics({status}:{status:string}) {
  const [result,setResult]=useState<Diagnostic>();const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  async function probe(){setBusy(true);setError('');try{setResult(await api<Diagnostic>('/api/replay/diagnostics'));}catch(e){setError(e instanceof Error?e.message:'诊断失败');}finally{setBusy(false);}}
  useEffect(()=>{void probe();},[status]);
  return <section className="panel replay-diagnostics"><div className="panel-head"><h2><Search size={17}/>回放接口诊断</h2><button className="button small" disabled={busy} onClick={()=>void probe()}><RefreshCw size={14}/>{busy?'检测中…':'重新检测'}</button></div><div className="diagnostic-content">{result?<><div className={`diagnostic-outcome ${result.status==='ready'?'ready':''}`}><span className={`status-dot ${result.status==='ready'?'green':'amber'}`}/><strong>{result.status==='ready'?'回放 API 已就绪':'需要处理连接条件'}</strong><p>{result.detail}</p></div><div className="diagnostic-next-step"><strong>下一步</strong><p>{result.status==='ready'?'在录像客户端核对时间与画面，播出期间请保持游戏来源向前。':result.restartRequired?'配置已变更，请重新打开录像客户端后再次检测。':result.configEnabled===false?'在游戏配置中启用 EnableReplayApi=1，再重新打开录像。':'确认本机已打开录像回放，并检查下方路径与端口状态。'}</p></div><details><summary>接口与配置详情</summary><div className="diagnostic-config"><span>Replay 开关</span><b>{result.configEnabled===true?<><Check size={14}/>已启用</>:result.configEnabled===false?'尚未启用':'未找到配置'}</b>{result.configPath&&<code>{result.configPath}</code>}</div><div className="diagnostic-endpoints">{result.endpoints.map(e=><div key={e.path}><code>{e.path}</code><span className={e.available?'green-text':'muted'}>{e.available?'可读取':e.statusCode?`HTTP ${e.statusCode}`:e.errorKind==='refused'?'端口未启动':e.errorKind||'不可用'}</span></div>)}</div></details>{result.playback&&<p className="muted">当前回放 {Math.floor(result.playback.time/60)}:{String(Math.floor(result.playback.time%60)).padStart(2,'0')} · {result.playback.speed}× · {result.playback.paused?'已暂停':'播放中'}</p>}<small className="muted">检测时间 {new Date(result.lastProbeAt).toLocaleTimeString('zh-CN')}</small></>:<p className="muted">检查本机 2999 端口、Replay 路径与游戏配置。</p>}{error&&<p className="request-error">{error}</p>}</div></section>;
}
