import { useEffect, useRef, useState } from 'react';
import { Activity, ArrowDownToLine, ArrowRight, AudioLines, Check, ChevronDown, ChevronRight, CircleHelp, Clapperboard, Clock3, Copy, Database, ExternalLink, Focus, Gamepad2, LayoutDashboard, Maximize2, Monitor, Pause, Play, Radio, RotateCcw, Settings2, ShieldCheck, Swords, Trophy, Users, Wifi, Zap } from 'lucide-react';
import type { BroadcastState, Champion, Phase, Player, Scene, Side, StateContext } from '../shared/types';
import { championFor, getTeam, gold, outputUrl, playerKda, sceneInfo, time } from './lib';
import { useBroadcast } from './useBroadcast';
import { Brand } from './components/Icons';
import { BroadcastCanvas, ChampionImage, EconomyChart } from './components/BroadcastCanvas';
import { ObsLivePreview, type ObsPreviewStatus } from './components/ObsLivePreview';
import { PlayerBuild } from './components/PlayerBuild';
import { BroadcastLook } from './components/BroadcastLook';
import { LiveData } from './pages/LiveData';
import { Management } from './pages/Management';
import { Settings } from './pages/Settings';
import { IncomeControls } from './components/ObserverGraphics';
import { FearlessControls, usedDraftChampions } from './components/FearlessControls';
import { GameTime, GameClockConnectionProvider } from './components/GameTime';

import { WorkflowRail, StudioOutputDock, WrapUp, type WorkflowPage } from './components/DirectorWorkflow';
import { SceneCard } from './components/SceneCard';
import { MatchLifecycle } from './components/MatchLifecycle';
type Page=WorkflowPage;
const scenes=Object.keys(sceneInfo) as Scene[];
const phaseLabels:Record<Phase,string>={pregame:'赛前准备',draft:'BP 阶段',live:'局内直播',postgame:'赛后复盘'};
const navItems=[{id:'studio' as Page,name:'导播工作台',icon:LayoutDashboard},{id:'draft' as Page,name:'BP 与阵容',icon:Swords},{id:'data' as Page,name:'实时数据',icon:Activity},{id:'manage' as Page,name:'赛事与素材',icon:Trophy}];
const connectionNames={lcu:'英雄联盟客户端',live:'局内实时数据',replay:'录像与回放',obs:'OBS 直播引擎'};

export default function App() {
  const broadcast=useBroadcast();const {state,champions,connected,error,toast,notify,send}=broadcast;
  const [page,setPage]=useState<Page>('studio');
  const [streamReady,setStreamReady]=useState(false);
  const [managementTab,setManagementTab]=useState<'schedule'|'recordings'>('schedule');
  const navigate=(next:Page)=>{if(next==='manage')setManagementTab('schedule');setPage(next);};
  useEffect(()=>{if(state?.connections.obs.status!=='connected')setStreamReady(false);},[state?.connections.obs.status]);
  useEffect(()=>{window.scrollTo(0,0);},[page]);
  const output=location.pathname.startsWith('/overlay');const remote=location.pathname.startsWith('/remote');
  useEffect(()=>{document.body.classList.toggle('overlay-body',output);document.documentElement.classList.toggle('overlay-document',output);return()=>{document.body.classList.remove('overlay-body');document.documentElement.classList.remove('overlay-document');};},[output]);
  useEffect(()=>{
    if(output||remote)return;
    const handler=(e:KeyboardEvent)=>{
      const target=e.target instanceof Element?e.target:null;
      if(target?.closest('input,textarea,select,[contenteditable]')||e.ctrlKey||e.metaKey||e.altKey)return;
      if(page!=='studio')return;
      if(e.repeat){if(e.key==='Enter'&&target?.closest('.scene-card,.take-button'))e.preventDefault();return;}
      const scene=scenes.find(s=>sceneInfo[s].shortcut.toLowerCase()===e.key.toLowerCase());
      if(scene){e.preventDefault();void send({type:'preview-scene',scene}).catch(()=>{});}
      // A selected scene card retains focus. Enter must take the current preview
      // even after another shortcut changes it, without activating the old card.
      if(e.key==='Enter'&&(!target?.closest('button,a,summary,[role=button]')||target.closest('.scene-card'))){e.preventDefault();void send({type:'take'}).then(()=>notify('已切入节目输出')).catch(()=>{});}
      if(e.key===' '&&state?.mode==='demo'&&!(e.target as HTMLElement)?.closest('button,a,summary,[role=button]')){e.preventDefault();void send({type:'demo-pause',paused:!state.paused}).catch(()=>{});}
    };window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);
  },[output,remote,page,state?.paused,state?.mode,send,notify]);
  if(!state)return <div className={`loading-screen ${output?'output-loading':''}`}><Brand/><span className="loading-dot"/><h2>{error?'本地服务尚未连接':'正在连接导播工作站'}</h2><p>{error||'载入赛事、素材与节目状态'}</p>{error&&<button className="button primary" onClick={()=>location.reload()}>重新连接</button>}</div>;
  const ctx={state,champions,send,notify};
  if(output)return <GameClockConnectionProvider value={connected}><BroadcastCanvas state={state} champions={champions} scene={new URLSearchParams(location.search).get('preview')==='1'?state.previewScene:state.programScene} output/>{!connected&&<div className="output-offline">导播服务中断 · 保留最后画面</div>}</GameClockConnectionProvider>;
  if(remote)return <GameClockConnectionProvider value={connected}><Remote {...ctx} connected={connected} toast={toast}/></GameClockConnectionProvider>;
  const titles={studio:['导播工作台','从预监到播出，每一次切换都尽在掌握。'],draft:['BP 与阵容','编排双方英雄选择，呈现每一个决策时刻。'],data:['实时数据','读懂比赛走势，捕捉选手与团队的关键表现。'],manage:['赛事与素材','准备赛程、阵容与视觉素材，让赛事随时就绪。'],settings:['连接与输出','连接比赛信号，设置画面、声音与直播输出。'],help:['使用指南','从赛事准备开始，完成一场精彩转播。'],wrap:['赛后收尾','停止本场输出，保存对局数据，准备下一场转播。']};
  return <GameClockConnectionProvider value={connected}><div className={'app-shell page-'+page}><aside className="sidebar"><div className="sidebar-brand"><Brand/><span className="brand-edition">ARENA</span></div><div className="workspace-label">导播空间</div><nav aria-label="主导航">{navItems.map(item=><button key={item.id} title={item.name} aria-current={page===item.id?'page':undefined} className={`nav-item ${page===item.id?'active':''}`} onClick={()=>setPage(item.id)}><item.icon size={19}/><span>{item.name}</span>{page===item.id&&<span className="nav-active-dot"/>}</button>)}</nav><div className="sidebar-divider"/><div className="workspace-label">工作站设置</div><button title="连接与输出" aria-current={page==='settings'?'page':undefined} className={`nav-item ${page==='settings'?'active':''}`} onClick={()=>setPage('settings')}><Settings2 size={19}/><span>连接与输出</span></button><button title="使用指南" aria-current={page==='help'?'page':undefined} className={`nav-item ${page==='help'?'active':''}`} onClick={()=>setPage('help')}><CircleHelp size={19}/><span>使用指南</span></button><div className="sidebar-session"><span className="session-label">当前播出</span><strong>{state.match.title}</strong><div><span className="blue-text">{getTeam(state,'blue')?.tag||'蓝色方'}</span><span>{state.match.blueScore} : {state.match.redScore}</span><span className="red-text">{getTeam(state,'red')?.tag||'红色方'}</span></div></div><div className="sidebar-bottom"><div className="local-status"><span className={`status-dot ${connected?'green':'red'}`}/><strong>本地工作站</strong><span>{connected?'已就绪':'连接中'}</span></div><small>RiftCast v0.2.0 <span>Windows</span></small><div className="legal-note">独立社区工具 · Riot Games 未背书</div></div></aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumbs"><span className="workspace-mark">RC</span><span>导播空间</span><ChevronRight size={13}/><strong>{titles[page][0]}</strong></div><div className="topbar-right"><span className={`mode-pill ${state.mode==='demo'?'demo':'live'}`}><span className="status-dot"/>{state.mode==='demo'?'演示模式':'本地实况'}</span><span className="topbar-divider"/><Clock3 size={14}/><span>{new Date().toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit'})}</span><div className="avatar">OB</div></div></header>
    <main><div className="page-heading"><div><div className="eyebrow"><span className="heading-dash"/> RIFTCAST ARENA <span>/ 赛事导播</span></div><h1>{titles[page][0]}</h1><p>{titles[page][1]}</p></div><div className="heading-actions"><button className="button" onClick={()=>navigate('manage')}><Trophy size={15}/>赛事准备</button><button className="button primary" onClick={()=>navigate('settings')}><Settings2 size={15}/>连接与输出</button></div></div>
    {!connected&&<div className="connection-alert"><Wifi size={16}/>{error||'数据同步已中断，正在重连。画面保留最后一次数据。'}</div>}
    <WorkflowRail state={state} page={page} onNavigate={navigate}/>
    {page==='studio'&&<MatchLifecycle {...ctx} onNextGame={()=>navigate('draft')} onReport={()=>navigate('studio')} onRecords={()=>{setManagementTab('recordings');setPage('manage');}}/>}
    {page==='studio'&&<Studio {...ctx} streamReady={streamReady} onSettings={()=>navigate('settings')} onManage={()=>navigate('manage')}/>}
    {page==='draft'&&<Draft {...ctx}/>}
    {page==='data'&&<Data {...ctx}/>}
    {page==='manage'&&<Management {...ctx} initialTab={managementTab} onOpenSettings={()=>navigate('settings')}/>}
    {page==='settings'&&<Settings {...ctx} outputReady={streamReady} onOpenStudio={()=>navigate('studio')} onOutputReady={setStreamReady}/>}
    {page==='help'&&<Help/>}
    {page==='wrap'&&<WrapUp {...ctx} streamReady={streamReady} onSettings={()=>navigate('settings')} onManage={()=>navigate('manage')} onRecords={()=>{setManagementTab('recordings');setPage('manage');}} onNextGame={()=>navigate('draft')} onReport={()=>navigate('studio')}/>}
    <footer className="workspace-footer"><span><ShieldCheck size={12}/> 本地数据 · 实时同步</span><span>{state.mode==='demo'?'当前数据为虚构演示数据':'本机客户端数据 · 缺失字段以 — 显示'}<span className="footer-dot">·</span>1920 × 1080 输出</span></footer>
    </main></div>{toast&&<div className="toast"><Check size={16}/>{toast}</div>}</div></GameClockConnectionProvider>;
}

function Studio({state,champions,send,notify,onSettings,onManage,streamReady}:StateContext&{onSettings:()=>void;onManage:()=>void;streamReady:boolean}) {
  const blue=getTeam(state,'blue');const red=getTeam(state,'red');
  const [eventFilter,setEventFilter]=useState('all');
  const [detailsOpen,setDetailsOpen]=useState(false);
  const latestState=useRef(state);latestState.current=state;
  const [sampledState,setSampledState]=useState(state);
  useEffect(()=>{const timer=window.setInterval(()=>{if(!document.hidden)setSampledState(latestState.current);},1000);return()=>window.clearInterval(timer);},[]);
  const quickScenes:Scene[]=['live','teamfight','draft','income'];
  const selectScene=(scene:Scene)=>{void send({type:'preview-scene',scene}).catch(()=>{});};
  const card=(scene:Scene)=><SceneCard key={scene} {...{state,sampledState,champions,scene}} onSelect={selectScene}/>;
  const statsLabel=(p:Player)=>state.mode==='demo'?'演示':p.statsAvailable===false?'未提供':p.statsSource==='ocr'?'OCR':p.statsSource==='api'?'API':'待采集';
  const statsDetail=(p:Player)=>state.mode==='demo'?'虚构演示数据':p.statsAvailable===false?'当前对局未提供有效 KDA 与补刀，等待计分板采样':p.statsSource==='ocr'?`观战计分板 OCR · 采样 ${p.statsSampledAt||'时间未提供'} · ${p.statsSampledAt&&p.statsExpiresAt&&Number.isFinite(Date.parse(p.statsExpiresAt)-Date.parse(p.statsSampledAt))?`${Math.max(0,(Date.parse(p.statsExpiresAt)-Date.parse(p.statsSampledAt))/1000)} 秒有效`:'有效期未提供'}`:p.statsSource==='api'?`局内 API 的 KDA 与补刀${p.statsSampledAt?` · 采样 ${p.statsSampledAt}`:''}`:'等待对局统计采集';
  const statsAvailable=(p:Player)=>state.mode==='demo'||p.statsAvailable!==false;
  const teamKills=(side:Side)=>state.mode==='live'&&(!state.players.some(p=>p.team===side)||state.players.some(p=>p.team===side&&p.statsAvailable===false))?'—':state.stats[side].kills;
  return <><div className="match-bar"><div className="match-identity"><div className="match-icon"><Trophy size={20}/></div><div><strong>{state.match.title}</strong><span>{state.match.subtitle} <b>·</b> {state.match.format} <b>·</b> 第 {state.match.game} 局</span></div></div><div className="match-versus"><span className="blue-text">{blue?.tag}</span><b>{state.match.blueScore}<i>:</i>{state.match.redScore}</b><span className="red-text">{red?.tag}</span></div><button className="button small match-change" onClick={onManage}>更换比赛</button><div className="match-time"><span className="status-dot green"/><GameTime state={state}/><small>比赛时间</small></div></div>
  <div className="phase-bar"><div className="phases">{(Object.keys(phaseLabels) as Phase[]).map((phase,i)=><button key={phase} className={state.phase===phase?'selected':''} onClick={()=>void send({type:'set-phase',phase}).catch(()=>{})}><span>{String(i+1).padStart(2,'0')}</span>{phaseLabels[phase]}{i<3&&<ChevronRight size={13}/>}</button>)}</div><div className="demo-controls">{state.mode==='demo'?<><span>演示数据</span><button title={state.paused?'播放演示':'暂停演示'} onClick={()=>void send({type:'demo-pause',paused:!state.paused}).catch(()=>{})}>{state.paused?<Play size={14}/>:<Pause size={14}/>}</button><button title="重置演示" onClick={()=>void send({type:'demo-reset'}).catch(()=>{})}><RotateCcw size={13}/></button></>:<span><Activity size={13}/> 客户端同步</span>}</div></div>
  <section className="studio-stage" aria-label="节目、预监与快捷切入">
    <div className="program-stack"><MonitorPane kind="program" purpose="program" {...{state,champions}}/><StudioOutputDock {...{notify,onSettings,streamReady}}/></div>
    <div className="studio-preview-column"><MonitorPane kind="preview" {...{state,champions}}/>
      <div className="take-bar"><div className="take-route"><span className="route-preview"><i/>待切入 <strong>{sceneInfo[state.previewScene].name}</strong></span></div><button className="take-button" disabled={state.previewScene===state.programScene} onClick={()=>void send({type:'take'}).then(()=>notify('预监画面已切入节目')).catch(()=>{})}><Zap size={15} fill="currentColor"/>切入节目<kbd>Enter</kbd></button></div>
      <section className="quick-scenes scenes-panel"><div className="quick-scenes-heading"><Clapperboard size={13}/><span>常用切入</span><small>点击选择预监</small></div><div className="scene-grid">{quickScenes.map(card)}</div></section>
    </div>
  </section>
  <section className="studio-scene-shelf scenes-panel" aria-label="其他可切入画面"><div className="scene-grid">{scenes.filter(scene=>!quickScenes.includes(scene)).map(card)}</div></section>
  <div className="studio-operation-note"><span><kbd>1–9</kbd> / <kbd>T</kbd> / <kbd>G</kbd> 选择预监 <ArrowRight size={12}/> <kbd>Enter</kbd> 切入节目</span><span>预监每秒更新 · 场景卡显示 HUD 包装</span></div>
  <details className="studio-details" open={detailsOpen} onToggle={event=>setDetailsOpen(event.currentTarget.open)}><summary>画面包装与对局详情<ChevronDown size={15}/></summary>{detailsOpen&&<><BroadcastLook {...{state,champions,send,notify}}/><div className="studio-grid"><div className="studio-main">
    <IncomeControls {...{state,champions,send,notify}}/><section className="panel lineup-panel"><div className="panel-head"><h2><Users size={16}/>双方阵容</h2><span className="muted">{state.players.length} 名选手 <span className="tiny-divider">/</span> {state.mode==='demo'?'演示数据':'当前对局 · API / OCR'}</span></div><div className="roster-columns">{(['blue','red'] as const).map(side=><div key={side} className={`roster-team ${side}`}><div className="roster-team-head"><span className="team-letter" style={{background:getTeam(state,side)?.color}}>{getTeam(state,side)?.tag.slice(0,1)}</span><strong title="赛事设置中的战队简称">{getTeam(state,side)?.tag}</strong><span title="赛事设置中的战队资料">{getTeam(state,side)?.name} · 赛事资料</span><b>{teamKills(side)} <small>击杀</small></b></div><div className="roster-table-head"><span>选手 / 英雄</span><span>K / D / A</span><span>补刀</span><span>累计经济</span></div>{state.players.filter(p=>p.team===side).map(p=><button className={`roster-row ${state.selectedPlayerId===p.id?'selected':''}`} key={p.id} onClick={()=>void send({type:'select-player',playerId:state.selectedPlayerId===p.id?null:p.id}).catch(()=>{})}><span><ChampionImage champions={champions} id={p.championId}/><span><strong>{p.name}</strong><small>{p.role} · {p.championName}</small></span></span><span title={statsDetail(p)}>{statsAvailable(p)?playerKda(p):'—'}<small> · {statsLabel(p)}</small></span><span title={statsDetail(p)}>{statsAvailable(p)?p.cs:'—'}</span><span title={state.mode==='demo'?'虚构演示数据':p.goldSource==='ocr'?`观战计分板 OCR · ${p.goldSampledAt||''} · 累计金币`:p.goldSource==='api'?'客户端累计金币':'等待累计金币采集'}>{gold(p.gold)}</span></button>)}</div>)}</div><p className="data-source-note">{state.mode==='demo'?'当前显示虚构演示数据。':'选手与英雄来自当前对局；KDA、补刀和累计经济按各行采集来源更新。'} 战队名称与简称沿用赛事设置，可在“赛事与素材”中编辑。鼠标悬停统计数据可查看来源与采样时间。</p></section></div>
    <aside className="studio-aside"><section className="panel sources-panel"><div className="panel-head"><h2><Radio size={16}/>信号源</h2><button className="icon-button" title="配置连接" onClick={onSettings}><Settings2 size={15}/></button></div>{(Object.keys(connectionNames) as (keyof typeof connectionNames)[]).map(key=><div className="source-row" key={key}><div className={`source-icon ${state.connections[key].status==='connected'?'is-connected':''}`}>{key==='obs'?<Monitor size={16}/>:key==='lcu'?<Gamepad2 size={16}/>:key==='replay'?<Play size={16}/>:<Activity size={16}/>}</div><div><strong>{connectionNames[key]}</strong><small>{state.connections[key].status==='connected'?'已连接':state.connections[key].status==='connecting'?'正在连接':state.mode==='demo'&&['lcu','live'].includes(key)?'演示数据驱动':key==='replay'?'仅回放可用':'未连接'}</small></div><span className={`status-dot ${state.connections[key].status==='connected'?'green':'gray'}`}/></div>)}<button className="source-config" onClick={onSettings}>管理数据源<ChevronRight size={14}/></button></section>
    <section className="panel metrics-panel"><div className="panel-head"><h2><AudioLines size={16}/>对局速览</h2><span className="badge">{state.mode==='demo'?'演示':'实况'}</span></div><div className="metric-score"><strong className="blue-text">{teamKills('blue')}</strong><span>击杀</span><strong className="red-text">{teamKills('red')}</strong></div><div className="metric-split"><div><span>总经济</span><b className="blue-text">{gold(state.stats.blue.gold)}</b></div><div><span>总经济</span><b className="red-text">{gold(state.stats.red.gold)}</b></div></div><div className="gold-meter"><i style={{width:`${state.stats.blue.gold&&state.stats.red.gold?100*state.stats.blue.gold/(state.stats.blue.gold+state.stats.red.gold):50}%`}}/></div><div className="objective-summary"><span>防御塔 <b>{state.stats.blue.towers} : {state.stats.red.towers}</b></span><span>巨龙 <b>{state.stats.blue.dragons} : {state.stats.red.dragons}</b></span></div></section>
    <section className="panel events-panel"><div className="panel-head"><h2><Activity size={16}/>事件时间线</h2><span className="event-count">{state.events.length}</span></div><div className="event-tabs"><button className={eventFilter==='all'?'active':''} onClick={()=>setEventFilter('all')}>全部</button><button className={eventFilter==='objective'?'active':''} onClick={()=>setEventFilter('objective')}>地图资源</button></div><div className="event-feed">{state.events.filter(e=>eventFilter==='all'||/dragon|baron|tower|herald/i.test(e.type)).slice(-7).reverse().map(e=><div className="event-row" key={e.id}><span className={`event-line-dot ${e.team||''}`}/><div><small>{time(e.time)} <span>{e.type}</span></small><p>{e.text}</p></div></div>)}{!state.events.length&&<div className="empty-state"><Activity size={26}/><p>等待游戏事件</p><small>对局开始后，关键事件会出现在这里</small></div>}</div><button className="record-button" onClick={()=>void send({type:'save-recording'}).then(()=>notify('当前对局快照已保存到比赛记录')).catch(()=>{})}><ArrowDownToLine size={14}/>保存对局快照</button></section>
    <div className="tip-card"><div><Focus size={18}/><strong>把镜头留给精彩</strong></div><p>数字键选择预监场景，按 Enter 切入节目。所有 HUD 变更将同步到输出页。</p><span>导播快捷操作 <ArrowRight size={13}/></span></div></aside></div></>}</details></>;
}

function MonitorPane({state,kind,purpose='monitor'}:{state:BroadcastState;champions:Champion[];kind:'preview'|'program';purpose?:'program'|'monitor'}) {
  const scene=kind==='preview'?state.previewScene:state.programScene;
  const [previewStatus,setPreviewStatus]=useState<ObsPreviewStatus|null>(null);
  const live=previewStatus?.phase==='live';
  return <section className={`monitor-pane ${kind}`}><div className="monitor-label"><span><i/>{kind==='preview'?'PVW':'PGM'} <b>{kind==='preview'?'预监画面':'节目播出'}</b></span><span>{sceneInfo[scene].name}</span><a href={outputUrl(kind==='preview')} target="_blank" rel="noreferrer" title="打开 HUD 浏览器源"><Maximize2 size={13}/></a></div><ObsLivePreview kind={kind} purpose={purpose} connected={state.connections.obs.status==='connected'} onStatus={setPreviewStatus}/><div className="monitor-footer"><span><span className={`status-dot ${live?(kind==='program'?'red':'green'):'gray'}`}/> {live?kind==='program'?'节目合成画面':'每秒采样，可切入节目':previewStatus?.phase==='paused'?'预览已暂停':'等待实时画面'}</span><span>{live&&previewStatus.fps>0?`${previewStatus.fps.toFixed(1)} fps · `:''}16:9</span></div></section>;
}

function Draft({state,champions,send,notify}:StateContext) {
  const [slot,setSlot]=useState<{side:'blue'|'red';kind:'Picks'|'Bans';index:number}|null>(null);const [search,setSearch]=useState('');
  const assign=async(id:string)=>{if(!slot)return;const key=`${slot.side}${slot.kind}` as 'bluePicks'|'redPicks'|'blueBans'|'redBans';const values=[...state.draft[key]];values[slot.index]=id;try{await send({type:'set-draft',patch:{[key]:values}});setSlot(null);notify('BP 画面已更新');}catch{/* message handled by send */}};
  return <div className="draft-workspace"><section className="panel"><div className="panel-head"><h2><Swords size={17}/>BP 画面预览</h2><div className="inline-buttons"><button className="button small" onClick={()=>void send({type:'preview-scene',scene:'draft'}).catch(()=>{})}>设为预监</button><button className="button primary small" onClick={()=>void send({type:'take',scene:'draft'}).then(()=>notify('BP 已切入节目')).catch(()=>{})}>切入节目</button></div></div><BroadcastCanvas state={state} champions={champions} scene="draft"/><div className="draft-source-note">{state.mode==='demo'?'演示 BP · 点击下方槽位手动编排英雄':'本地 BP · LCU 可用时自动同步，手动修改可能被下一次同步覆盖'}</div></section><FearlessControls {...{state,champions,send,notify}}/><div className="draft-edit-grid">{(['blue','red'] as const).map(side=><section className="panel" key={side}><div className="panel-head"><h2 className={`${side}-text`}>{getTeam(state,side)?.tag} · {getTeam(state,side)?.name}</h2></div>{(['Picks','Bans'] as const).map(kind=><div key={kind} className="draft-slot-section"><span className="eyebrow">{kind==='Picks'?'英雄选择':'英雄禁用'}</span><div className="draft-slots">{Array.from({length:5},(_,i)=>{const id=state.draft[`${side}${kind}` as keyof typeof state.draft] as string[];return <button key={i} className={slot?.side===side&&slot.kind===kind&&slot.index===i?'selected':''} onClick={()=>setSlot({side,kind,index:i})}><ChampionImage champions={champions} id={id[i]}/><strong>{championFor(champions,id[i])?.name||'选择英雄'}</strong><small>{kind==='Picks'?getTeam(state,side)?.players[i]?.name:`BAN ${i+1}`}</small></button>;})}</div></div>)}</section>)}</div>{slot&&<section className="panel champion-picker"><div className="panel-head"><h2>选择英雄 · {slot.side==='blue'?'蓝色方':'红色方'} {slot.kind==='Picks'?'PICK':'BAN'} {slot.index+1}</h2><div className="inline-buttons"><input placeholder="搜索英雄名称 / 英文 ID" value={search} onChange={e=>setSearch(e.target.value)}/><button className="button small" onClick={()=>void assign('')}>清空槽位</button><button className="button small" onClick={()=>setSlot(null)}>关闭</button></div></div><div className="champion-picker-grid">{champions.filter(c=>`${c.name} ${c.id}`.toLowerCase().includes(search.toLowerCase())).map(c=><button key={c.id} disabled={slot.kind==='Picks'&&usedDraftChampions(state).has(c.id)} title={usedDraftChampions(state).has(c.id)?'全局 BP：前局已使用':c.name} onClick={()=>void assign(c.id)}><ChampionImage champions={champions} id={c.id}/><span>{c.name}</span></button>)}</div></section>}</div>;
}

function Data(ctx:StateContext){return <LiveData {...ctx}/>;}

function Remote({state,champions,send,notify,connected,toast}:StateContext&{connected:boolean;toast:string}) {
  return <div className="remote-page"><header><Brand/><span className={`badge ${connected?'green-text':'red-text'}`}>{connected?'已同步':'离线'}</span></header><h1>移动导播台</h1><p className="muted">{state.match.title} · {state.mode==='demo'?'演示模式':'本地实况'}</p><div className="monitor-row"><MonitorPane kind="preview" state={state} champions={champions}/><MonitorPane kind="program" state={state} champions={champions}/></div><button className="take-button" onClick={()=>void send({type:'take'}).then(()=>notify('已切入节目')).catch(()=>{})}><Zap size={18}/>切入节目 · {sceneInfo[state.previewScene].name}</button><div className="remote-scene-grid">{scenes.map(scene=><button className={`button ${state.previewScene===scene?'primary':''}`} key={scene} onClick={()=>void send({type:'preview-scene',scene}).catch(()=>{})}>{sceneInfo[scene].name}{state.programScene===scene&&<span>PGM</span>}</button>)}</div><section className="panel"><div className="panel-head"><h2>HUD 控制</h2></div>{(['scoreboard','players','objectives','ticker','goldDiff'] as const).map((key,i)=><label className="remote-toggle" key={key}><span>{['计分板','十人装备表','地图资源','底部信息条','经济差'][i]}</span><input type="checkbox" checked={state.overlay[key]} onChange={e=>void send({type:'set-overlay',patch:{[key]:e.target.checked}}).catch(()=>{})}/></label>)}</section>{toast&&<div className="toast">{toast}</div>}</div>;
}
function Help(){return <div className="help-grid">{[{n:'01',title:'准备赛事与素材',text:'在「赛事与素材」录入战队、选手和赛程，上传战队标志、选手照片、赞助商图片。加载要转播的比赛。',icon:Trophy},{n:'02',title:'连接本机游戏',text:'在「连接与输出」切换到本地实况，填写客户端 lockfile 路径。BP 读取 LCU，局内数据读取 2999 端口。启动游戏后检测连接。',icon:Gamepad2},{n:'03',title:'核对内置直播引擎',text:'在「连接与输出」核对内置 OBS 的合成预览。游戏捕获、1920 × 1080 HUD 与系统声音自动配置，需要解说时选择麦克风并应用。',icon:Monitor},{n:'04',title:'预监、切换与收尾',text:'导播工作台按 1–9 / T / G 选场景，Enter 切入节目。节目使用原生显示，预监每秒更新。推流与录制可在工作台控制；赛后通过「赛后收尾」停输出并保存数据。多人控制需开启局域网并配对。',icon:Clapperboard}].map(item=><section className="panel help-card" key={item.n}><div><item.icon size={24}/><span>{item.n}</span></div><h2>{item.title}</h2><p>{item.text}</p></section>)}<section className="panel help-limits"><h2>当前版本的能力范围</h2><p>RiftCast 首版支持赛前、BP、局内、赛后的场景与 HUD 输出。演示模式使用虚构数据，实时数据保留来源；观战 HUD 经济识别与人工校准补充团队经济。</p><p>实时胜率模型、自动镜头跟随、经验排行、英雄池历史和摄像采集将需要进一步接入与验证。摄像头可通过外部 OBS 高级模式制作，采访场景负责展示选手名牌。Replay 控制只用于已启用 Replay API 的录像环境。</p><a href="https://developer.riotgames.com/docs/lol" target="_blank" rel="noreferrer">Riot 官方接口文档 <ExternalLink size={13}/></a></section></div>;}
